// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAuditLogByComplex = `-- name: GetAuditLogByComplex :many
SELECT id, user_id, complex_id, action, entity_type, entity_id, old_value, new_value, ip_address, created_at FROM audit_log
WHERE complex_id = $1
  AND (created_at, id) < ($2, $3)
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type GetAuditLogByComplexParams struct {
	ComplexID   pgtype.UUID        `json:"complex_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
	Limit       int32              `json:"limit"`
}

func (q *Queries) GetAuditLogByComplex(ctx context.Context, arg GetAuditLogByComplexParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, getAuditLogByComplex,
		arg.ComplexID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ComplexID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.OldValue,
			&i.NewValue,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_log (user_id, complex_id, action, entity_type, entity_id, old_value, new_value, ip_address)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, complex_id, action, entity_type, entity_id, old_value, new_value, ip_address, created_at
`

type InsertAuditLogParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	ComplexID  pgtype.UUID `json:"complex_id"`
	Action     string      `json:"action"`
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
	OldValue   []byte      `json:"old_value"`
	NewValue   []byte      `json:"new_value"`
	IpAddress  *netip.Addr `json:"ip_address"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.UserID,
		arg.ComplexID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.OldValue,
		arg.NewValue,
		arg.IpAddress,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ComplexID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.OldValue,
		&i.NewValue,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}
