// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: complexes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getComplexByID = `-- name: GetComplexByID :one
SELECT id, owner_id, name, slug, address, city, province, country_code, currency, phone, email, logo_url, cover_url, deposit_percentage, cancellation_hours, latitude, longitude, is_active, mp_access_token, mp_refresh_token, mp_user_id, deleted_at, created_at, updated_at, amenities, mp_token_expires_at FROM active_complexes
WHERE id = $1
`

// Reads active_complexes, not the table: this is the lookup behind the owner
// guard, the public booking link and the payment paths, and none of them may
// ever resolve a soft-deleted venue. See the soft-delete cascade in db/migrations/001_init.sql.
func (q *Queries) GetComplexByID(ctx context.Context, id pgtype.UUID) (ActiveComplex, error) {
	row := q.db.QueryRow(ctx, getComplexByID, id)
	var i ActiveComplex
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Address,
		&i.City,
		&i.Province,
		&i.CountryCode,
		&i.Currency,
		&i.Phone,
		&i.Email,
		&i.LogoUrl,
		&i.CoverUrl,
		&i.DepositPercentage,
		&i.CancellationHours,
		&i.Latitude,
		&i.Longitude,
		&i.IsActive,
		&i.MpAccessToken,
		&i.MpRefreshToken,
		&i.MpUserID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Amenities,
		&i.MpTokenExpiresAt,
	)
	return i, err
}

const getComplexBySlug = `-- name: GetComplexBySlug :one
SELECT id, owner_id, name, slug, address, city, province, country_code, currency, phone, email, logo_url, cover_url, deposit_percentage, cancellation_hours, latitude, longitude, is_active, mp_access_token, mp_refresh_token, mp_user_id, deleted_at, created_at, updated_at, amenities, mp_token_expires_at FROM active_complexes
WHERE slug = $1
`

// Reads active_complexes: the slug is the public URL, so this is the storefront.
// A deleted venue keeps its slug (the name stays reserved) and must answer 404,
// not serve a page. See the soft-delete cascade in db/migrations/001_init.sql.
func (q *Queries) GetComplexBySlug(ctx context.Context, slug string) (ActiveComplex, error) {
	row := q.db.QueryRow(ctx, getComplexBySlug, slug)
	var i ActiveComplex
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Address,
		&i.City,
		&i.Province,
		&i.CountryCode,
		&i.Currency,
		&i.Phone,
		&i.Email,
		&i.LogoUrl,
		&i.CoverUrl,
		&i.DepositPercentage,
		&i.CancellationHours,
		&i.Latitude,
		&i.Longitude,
		&i.IsActive,
		&i.MpAccessToken,
		&i.MpRefreshToken,
		&i.MpUserID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Amenities,
		&i.MpTokenExpiresAt,
	)
	return i, err
}

const getComplexesByOwner = `-- name: GetComplexesByOwner :many
SELECT c.id, c.owner_id, c.name, c.slug, c.address, c.city, c.province, c.country_code, c.currency, c.phone, c.email, c.logo_url, c.cover_url, c.deposit_percentage, c.cancellation_hours, c.latitude, c.longitude, c.is_active, c.mp_access_token, c.mp_refresh_token, c.mp_user_id, c.deleted_at, c.created_at, c.updated_at, c.amenities, c.mp_token_expires_at, (
    SELECT COUNT(*) FROM active_courts ct WHERE ct.complex_id = c.id
) AS court_count
FROM active_complexes c
WHERE c.owner_id = $1
ORDER BY c.created_at DESC
`

type GetComplexesByOwnerRow struct {
	ID                pgtype.UUID        `json:"id"`
	OwnerID           pgtype.UUID        `json:"owner_id"`
	Name              string             `json:"name"`
	Slug              string             `json:"slug"`
	Address           string             `json:"address"`
	City              string             `json:"city"`
	Province          string             `json:"province"`
	CountryCode       string             `json:"country_code"`
	Currency          string             `json:"currency"`
	Phone             string             `json:"phone"`
	Email             pgtype.Text        `json:"email"`
	LogoUrl           pgtype.Text        `json:"logo_url"`
	CoverUrl          pgtype.Text        `json:"cover_url"`
	DepositPercentage int32              `json:"deposit_percentage"`
	CancellationHours int32              `json:"cancellation_hours"`
	Latitude          pgtype.Float8      `json:"latitude"`
	Longitude         pgtype.Float8      `json:"longitude"`
	IsActive          bool               `json:"is_active"`
	MpAccessToken     pgtype.Text        `json:"mp_access_token"`
	MpRefreshToken    pgtype.Text        `json:"mp_refresh_token"`
	MpUserID          pgtype.Text        `json:"mp_user_id"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Amenities         []string           `json:"amenities"`
	MpTokenExpiresAt  pgtype.Timestamptz `json:"mp_token_expires_at"`
	CourtCount        int64              `json:"court_count"`
}

// Carries a court count, because the list is where an owner decides which club
// to work on and a club with no courts can take no booking at all — it looked
// identical to a finished one.
//
// A COUNT, not a "complete" flag: complete is a policy that moves every time a
// step is added to onboarding, and a flag would put that policy in the server
// where the client cannot see it change. The server says how many courts there
// are; what that means is the caller's business.
//
// Soft-deleted courts do not count. Deactivated ones do: a venue that switched
// a court off still has courts, and that is a different question. Neither do
// the courts of a soft-deleted venue, but that is now true by construction:
// active_courts cannot contain one.
//
// A scalar subquery rather than a LEFT JOIN and a GROUP BY. Reading from the
// views means `GROUP BY c.id` no longer covers the other columns: PostgreSQL's
// functional-dependency shortcut applies to a base table's primary key, and a
// view has none, so the join form needs all 26 columns spelled into the GROUP
// BY. The subquery says the same thing in one line and cannot drift from the
// column list.
func (q *Queries) GetComplexesByOwner(ctx context.Context, ownerID pgtype.UUID) ([]GetComplexesByOwnerRow, error) {
	rows, err := q.db.Query(ctx, getComplexesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetComplexesByOwnerRow
	for rows.Next() {
		var i GetComplexesByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Slug,
			&i.Address,
			&i.City,
			&i.Province,
			&i.CountryCode,
			&i.Currency,
			&i.Phone,
			&i.Email,
			&i.LogoUrl,
			&i.CoverUrl,
			&i.DepositPercentage,
			&i.CancellationHours,
			&i.Latitude,
			&i.Longitude,
			&i.IsActive,
			&i.MpAccessToken,
			&i.MpRefreshToken,
			&i.MpUserID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Amenities,
			&i.MpTokenExpiresAt,
			&i.CourtCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertComplex = `-- name: InsertComplex :one
INSERT INTO complexes (
    owner_id, name, slug,
    address, city, province, country_code, currency,
    phone, email, logo_url, cover_url,
    deposit_percentage, cancellation_hours,
    latitude, longitude, amenities
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
RETURNING id, owner_id, name, slug, address, city, province, country_code, currency, phone, email, logo_url, cover_url, deposit_percentage, cancellation_hours, latitude, longitude, is_active, mp_access_token, mp_refresh_token, mp_user_id, deleted_at, created_at, updated_at, amenities, mp_token_expires_at
`

type InsertComplexParams struct {
	OwnerID           pgtype.UUID   `json:"owner_id"`
	Name              string        `json:"name"`
	Slug              string        `json:"slug"`
	Address           string        `json:"address"`
	City              string        `json:"city"`
	Province          string        `json:"province"`
	CountryCode       string        `json:"country_code"`
	Currency          string        `json:"currency"`
	Phone             string        `json:"phone"`
	Email             pgtype.Text   `json:"email"`
	LogoUrl           pgtype.Text   `json:"logo_url"`
	CoverUrl          pgtype.Text   `json:"cover_url"`
	DepositPercentage int32         `json:"deposit_percentage"`
	CancellationHours int32         `json:"cancellation_hours"`
	Latitude          pgtype.Float8 `json:"latitude"`
	Longitude         pgtype.Float8 `json:"longitude"`
	Amenities         []string      `json:"amenities"`
}

func (q *Queries) InsertComplex(ctx context.Context, arg InsertComplexParams) (Complex, error) {
	row := q.db.QueryRow(ctx, insertComplex,
		arg.OwnerID,
		arg.Name,
		arg.Slug,
		arg.Address,
		arg.City,
		arg.Province,
		arg.CountryCode,
		arg.Currency,
		arg.Phone,
		arg.Email,
		arg.LogoUrl,
		arg.CoverUrl,
		arg.DepositPercentage,
		arg.CancellationHours,
		arg.Latitude,
		arg.Longitude,
		arg.Amenities,
	)
	var i Complex
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Address,
		&i.City,
		&i.Province,
		&i.CountryCode,
		&i.Currency,
		&i.Phone,
		&i.Email,
		&i.LogoUrl,
		&i.CoverUrl,
		&i.DepositPercentage,
		&i.CancellationHours,
		&i.Latitude,
		&i.Longitude,
		&i.IsActive,
		&i.MpAccessToken,
		&i.MpRefreshToken,
		&i.MpUserID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Amenities,
		&i.MpTokenExpiresAt,
	)
	return i, err
}

const listComplexesNeedingMPRefresh = `-- name: ListComplexesNeedingMPRefresh :many
SELECT id, owner_id, name, slug, address, city, province, country_code, currency, phone, email, logo_url, cover_url, deposit_percentage, cancellation_hours, latitude, longitude, is_active, mp_access_token, mp_refresh_token, mp_user_id, deleted_at, created_at, updated_at, amenities, mp_token_expires_at FROM active_complexes
WHERE mp_refresh_token IS NOT NULL
  AND is_active = true
  AND (mp_token_expires_at IS NULL OR mp_token_expires_at < now() + interval '30 days')
`

// Connected complexes whose OAuth token has no known expiry (never recorded
// one, e.g. rows connected before this column existed) or expires within 30
// days. cronRefreshMPTokens used to refresh every connected complex on every
// 12h tick regardless of how recently its token was issued; this narrows
// that to the complexes that actually need it.
func (q *Queries) ListComplexesNeedingMPRefresh(ctx context.Context) ([]ActiveComplex, error) {
	rows, err := q.db.Query(ctx, listComplexesNeedingMPRefresh)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActiveComplex
	for rows.Next() {
		var i ActiveComplex
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Slug,
			&i.Address,
			&i.City,
			&i.Province,
			&i.CountryCode,
			&i.Currency,
			&i.Phone,
			&i.Email,
			&i.LogoUrl,
			&i.CoverUrl,
			&i.DepositPercentage,
			&i.CancellationHours,
			&i.Latitude,
			&i.Longitude,
			&i.IsActive,
			&i.MpAccessToken,
			&i.MpRefreshToken,
			&i.MpUserID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Amenities,
			&i.MpTokenExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteComplex = `-- name: SoftDeleteComplex :execrows
UPDATE complexes
SET deleted_at = NOW(),
    is_active = false
WHERE id = $1
  AND deleted_at IS NULL
`

// :execrows, so the caller can tell "deleted it" from "it was already deleted"
// without a separate SELECT. ComplexModel.SoftDeleteCascade is the only caller
// and runs this inside the transaction that also counts the courts the
// soft-delete cascade trigger closes.
func (q *Queries) SoftDeleteComplex(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteComplex, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateComplex = `-- name: UpdateComplex :one
UPDATE complexes
SET name = $1,
    slug = $2,
    address = $3,
    city = $4,
    province = $5,
    phone = $6,
    email = $7,
    logo_url = $8,
    cover_url = $9,
    deposit_percentage = $10,
    cancellation_hours = $11,
    is_active = $12,
    latitude = $13,
    longitude = $14,
    amenities = $15
WHERE id = $16
  AND deleted_at IS NULL
  AND updated_at = $17
RETURNING id, owner_id, name, slug, address, city, province, country_code, currency, phone, email, logo_url, cover_url, deposit_percentage, cancellation_hours, latitude, longitude, is_active, mp_access_token, mp_refresh_token, mp_user_id, deleted_at, created_at, updated_at, amenities, mp_token_expires_at
`

type UpdateComplexParams struct {
	Name              string             `json:"name"`
	Slug              string             `json:"slug"`
	Address           string             `json:"address"`
	City              string             `json:"city"`
	Province          string             `json:"province"`
	Phone             string             `json:"phone"`
	Email             pgtype.Text        `json:"email"`
	LogoUrl           pgtype.Text        `json:"logo_url"`
	CoverUrl          pgtype.Text        `json:"cover_url"`
	DepositPercentage int32              `json:"deposit_percentage"`
	CancellationHours int32              `json:"cancellation_hours"`
	IsActive          bool               `json:"is_active"`
	Latitude          pgtype.Float8      `json:"latitude"`
	Longitude         pgtype.Float8      `json:"longitude"`
	Amenities         []string           `json:"amenities"`
	ID                pgtype.UUID        `json:"id"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

// H-14: an unconditional UPDATE let two concurrent edits race — each loads the
// row, applies its own fields, and writes every column back, so whichever
// request commits second silently overwrites the first's change with a value
// it read before that first write existed. Both callers got 200 and neither
// was told.
//
// `updated_at = $17` is the optimistic-concurrency precondition: the caller
// must echo back the `updated_at` it read when it loaded the row. If another
// write landed in between, that timestamp has already moved and this UPDATE
// matches zero rows instead of clobbering the other request's change.
// ComplexModel.Update turns zero rows into ErrRecordNotFound, which the
// handler already maps to a 409 edit-conflict response (it previously existed
// only to cover a row deleted out from under the request) — so a refused
// update now reaches the caller as a conflict to retry, not as data loss.
func (q *Queries) UpdateComplex(ctx context.Context, arg UpdateComplexParams) (Complex, error) {
	row := q.db.QueryRow(ctx, updateComplex,
		arg.Name,
		arg.Slug,
		arg.Address,
		arg.City,
		arg.Province,
		arg.Phone,
		arg.Email,
		arg.LogoUrl,
		arg.CoverUrl,
		arg.DepositPercentage,
		arg.CancellationHours,
		arg.IsActive,
		arg.Latitude,
		arg.Longitude,
		arg.Amenities,
		arg.ID,
		arg.UpdatedAt,
	)
	var i Complex
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Address,
		&i.City,
		&i.Province,
		&i.CountryCode,
		&i.Currency,
		&i.Phone,
		&i.Email,
		&i.LogoUrl,
		&i.CoverUrl,
		&i.DepositPercentage,
		&i.CancellationHours,
		&i.Latitude,
		&i.Longitude,
		&i.IsActive,
		&i.MpAccessToken,
		&i.MpRefreshToken,
		&i.MpUserID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Amenities,
		&i.MpTokenExpiresAt,
	)
	return i, err
}
