// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUnverifiedStaleUsers = `-- name: DeleteUnverifiedStaleUsers :exec
DELETE FROM users
WHERE email_verified = false
AND created_at < NOW() - INTERVAL '7 days'
AND NOT EXISTS (SELECT 1 FROM complexes WHERE owner_id = users.id)
`

func (q *Queries) DeleteUnverifiedStaleUsers(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteUnverifiedStaleUsers)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, first_name, last_name, phone, role, is_active, failed_login_attempts, locked_until, last_failed_login, email_verified, created_at, updated_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Role,
		&i.IsActive,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastFailedLogin,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, first_name, last_name, phone, role, is_active, failed_login_attempts, locked_until, last_failed_login, email_verified, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Role,
		&i.IsActive,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastFailedLogin,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (email, password_hash, first_name, last_name, phone, role)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, password_hash, first_name, last_name, phone, role, is_active, failed_login_attempts, locked_until, last_failed_login, email_verified, created_at, updated_at
`

type InsertUserParams struct {
	Email        string   `json:"email"`
	PasswordHash []byte   `json:"password_hash"`
	FirstName    string   `json:"first_name"`
	LastName     string   `json:"last_name"`
	Phone        string   `json:"phone"`
	Role         UserRole `json:"role"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Role,
		&i.IsActive,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastFailedLogin,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setEmailVerified = `-- name: SetEmailVerified :exec
UPDATE users SET email_verified = true WHERE id = $1
`

func (q *Queries) SetEmailVerified(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setEmailVerified, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = $1,
    first_name = $2,
    last_name = $3,
    phone = $4,
    is_active = $5,
    email_verified = $6
WHERE id = $7
RETURNING id, email, password_hash, first_name, last_name, phone, role, is_active, failed_login_attempts, locked_until, last_failed_login, email_verified, created_at, updated_at
`

type UpdateUserParams struct {
	Email         string      `json:"email"`
	FirstName     string      `json:"first_name"`
	LastName      string      `json:"last_name"`
	Phone         string      `json:"phone"`
	IsActive      bool        `json:"is_active"`
	EmailVerified bool        `json:"email_verified"`
	ID            pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.IsActive,
		arg.EmailVerified,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Role,
		&i.IsActive,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastFailedLogin,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
