/**
 * Shared time/date string parsers.
 *
 * `noUncheckedIndexedAccess` makes `string.split(sep)[i]` typed as
 * `string | undefined`, so every ad-hoc "HH:MM"/"YYYY-MM-DD" parser across
 * the codebase needs a guard. These helpers centralize that guard in one
 * reviewed unit instead of scattering `!` assertions per call site.
 */

export interface HhMm {
  hours: number;
  minutes: number;
}

export interface Ymd {
  year: number;
  month: number;
  day: number;
}

/**
 * Parses a "HH:MM" string. Returns `null` when the string does not have
 * exactly two numeric segments (missing/extra segments, non-numeric parts).
 */
export function parseHhMm(time: string): HhMm | null {
  const parts = time.split(':');
  if (parts.length !== 2) return null;

  const [hoursPart, minutesPart] = parts;
  const hours = Number(hoursPart);
  const minutes = Number(minutesPart);
  if (!Number.isFinite(hours) || !Number.isFinite(minutes)) return null;

  return { hours, minutes };
}

/**
 * Parses a "YYYY-MM-DD" string. Returns `null` when the string does not
 * have exactly three numeric segments.
 */
export function parseYmd(date: string): Ymd | null {
  const parts = date.split('-');
  if (parts.length !== 3) return null;

  const [yearPart, monthPart, dayPart] = parts;
  const year = Number(yearPart);
  const month = Number(monthPart);
  const day = Number(dayPart);
  if (!Number.isFinite(year) || !Number.isFinite(month) || !Number.isFinite(day)) return null;

  return { year, month, day };
}

/**
 * Converts an "HH:MM" string to minutes since midnight, for slot comparison/
 * sorting. Callers pass either schema-validated API data (bookings, blocked
 * slots, court schedules) or slots generated by this module's own helpers, so
 * the `null`-parse branch is a type-level safety net, not an expected path —
 * it returns `0` rather than propagating `null` through arithmetic call sites.
 */
export function timeToMinutes(time: string): number {
  const parsed = parseHhMm(time);
  if (!parsed) return 0;
  return parsed.hours * 60 + parsed.minutes;
}

/**
 * Generates 30-minute "HH:MM" slots in `[from, to)`. `from`/`to` are always
 * caller-supplied constants or already-validated schedule times in practice;
 * a malformed bound returns an empty slot list rather than propagating
 * `null` through the loop.
 */
export function generateTimeSlots(from = '00:00', to = '24:00'): string[] {
  const slots: string[] = [];
  const start = parseHhMm(from);
  const end = to === '24:00' ? { hours: 24, minutes: 0 } : parseHhMm(to);
  if (!start || !end) return slots;

  let h = start.hours;
  let m = start.minutes;
  while (h < end.hours || (h === end.hours && m < end.minutes)) {
    slots.push(`${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}`);
    m += 30;
    if (m >= 60) {
      m = 0;
      h++;
    }
  }
  return slots;
}

/**
 * Adds `minutes` to an "HH:MM" string, wrapping past midnight (24h format).
 * The malformed-input branch returns the original string unchanged — a
 * defensive no-op rather than fabricating a time — since every call site
 * passes an already-validated "HH:MM" value (schedule/booking times).
 */
export function addMinutes(time: string, minutes: number): string {
  const parsed = parseHhMm(time);
  if (!parsed) return time;
  const total = parsed.hours * 60 + parsed.minutes + minutes;
  return `${String(Math.floor(total / 60) % 24).padStart(2, '0')}:${String(total % 60).padStart(2, '0')}`;
}
