package store

import (
	"reflect"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"

	"github.com/stodulski/vibe-server/internal/db"
)

// This file is the structural half of the userFromDB fix.
//
// Mapping a row to a domain struct by hand is a rule that has to be re-obeyed
// every time either struct grows, and it was already broken once: userFromDB
// mapped twelve of db.User's fifteen columns and dropped failed_login_attempts,
// locked_until and last_failed_login. Nothing failed, because the only caller of
// IsLocked reached its user through the other loader. Adding the three lines was
// the easy part; what follows is the part that stops the fourth line going
// missing the same way.
//
// The trigger is db.User itself. That struct is regenerated by `make sqlc`
// whenever a migration touches the users table, so it is the thing that moves.
// TestUserFromDBCarriesEveryColumn fails the moment it grows a field, and it
// fails again if a field is carried into the wrong place — which "did you
// remember" cannot detect and a non-zero check alone cannot either.

// userColumnsDeliberatelyNotMapped names db.User fields that userFromDB is meant
// to drop, with the reason. It is empty today: every column of users has a home
// on data.User. It exists so that dropping the next one is a decision somebody
// writes down here, rather than an omission that looks identical to a mistake.
var userColumnsDeliberatelyNotMapped = map[string]string{}

// fullyPopulatedDBUser is a db.User with every field set to a distinct non-zero
// value. Distinct matters: if the values were interchangeable, a mapper that
// assigned FirstName to LastName would satisfy every assertion below.
func fullyPopulatedDBUser() db.User {
	created := time.Date(2021, 3, 4, 5, 6, 7, 0, time.UTC)
	updated := time.Date(2022, 4, 5, 6, 7, 8, 0, time.UTC)
	locked := time.Date(2023, 5, 6, 7, 8, 9, 0, time.UTC)
	lastFailed := time.Date(2024, 6, 7, 8, 9, 10, 0, time.UTC)

	return db.User{
		ID:                  pgtype.UUID{Bytes: uuid.MustParse("11111111-2222-3333-4444-555555555555"), Valid: true},
		Email:               "mapped@example.test",
		PasswordHash:        []byte("hashed-password-bytes"),
		FirstName:           "MappedFirst",
		LastName:            "MappedLast",
		Phone:               "+5491100000042",
		Role:                db.UserRoleSuperadmin,
		IsActive:            true,
		FailedLoginAttempts: 7,
		LockedUntil:         pgtype.Timestamptz{Time: locked, Valid: true},
		LastFailedLogin:     pgtype.Timestamptz{Time: lastFailed, Valid: true},
		EmailVerified:       true,
		CreatedAt:           pgtype.Timestamptz{Time: created, Valid: true},
		UpdatedAt:           pgtype.Timestamptz{Time: updated, Valid: true},
	}
}

// TestUserFromDBCarriesEveryColumn walks db.User field by field and requires
// each one to arrive on the domain User with the same value.
//
// It fails in three distinct ways, and each one is a real defect it is meant to
// catch:
//
//   - db.User gains a field and fullyPopulatedDBUser leaves it zero. The
//     "must be populated" check fires, and whoever regenerated internal/db is
//     told to decide what happens to the new column instead of nothing
//     happening to it.
//   - userFromDB stops carrying a field. The per-field comparison fires and
//     names the column.
//   - userFromDB carries a field into the wrong place. Also the per-field
//     comparison, because every source value here is distinct.
func TestUserFromDBCarriesEveryColumn(t *testing.T) {
	source := fullyPopulatedDBUser()
	sourceVal := reflect.ValueOf(source)
	sourceType := sourceVal.Type()

	// Guard first: a source field left at its zero value would make the
	// comparison below vacuous for that column, so the fixture's completeness is
	// checked before it is trusted. This is the assertion that fires when
	// `make sqlc` adds a column.
	for i := range sourceType.NumField() {
		if sourceVal.Field(i).IsZero() {
			t.Fatalf("db.User.%s is zero in fullyPopulatedDBUser. If this column is new, "+
				"populate it here and either map it in userFromDB or record why not in "+
				"userColumnsDeliberatelyNotMapped — a column that is silently dropped and a "+
				"column that is deliberately dropped must not look the same",
				sourceType.Field(i).Name)
		}
	}

	mapped := userFromDB(source)
	mappedVal := reflect.ValueOf(*mapped)
	mappedType := mappedVal.Type()

	for i := range sourceType.NumField() {
		name := sourceType.Field(i).Name

		if reason, deliberate := userColumnsDeliberatelyNotMapped[name]; deliberate {
			t.Logf("db.User.%s is deliberately not mapped: %s", name, reason)
			continue
		}

		target := mappedVal.FieldByName(name)
		if !target.IsValid() {
			t.Errorf("db.User.%s has no field of the same name on data.User. Add one, or "+
				"record the omission in userColumnsDeliberatelyNotMapped", name)
			continue
		}

		want := comparableFieldValue(sourceVal.Field(i))
		got := comparableFieldValue(target)
		if !reflect.DeepEqual(want, got) {
			t.Errorf("column %s does not survive userFromDB: db.User has %v, data.User has %v",
				name, want, got)
		}
	}

	if mappedType.NumField() != sourceType.NumField() {
		t.Logf("data.User has %d fields and db.User has %d; the extras are domain-only and "+
			"are not checked here", mappedType.NumField(), sourceType.NumField())
	}
}

// TestUserFromDBCarriesTheLockoutColumns is the same property stated as three
// named assertions rather than a reflective sweep, so the regression is legible
// without decoding the loop above — and so the sweep cannot be weakened without
// this failing too.
//
// These three are singled out because of how they fail. LockedUntil is read by
// User.IsLocked, which reports "not locked" for a nil pointer. A mapper that
// drops the column therefore does not produce an error, a zero value that looks
// wrong, or a log line: it produces a confident, wrong "no" from a security
// check, for every caller that did not happen to load its user through the
// login path.
func TestUserFromDBCarriesTheLockoutColumns(t *testing.T) {
	source := fullyPopulatedDBUser()
	got := userFromDB(source)

	if got.FailedLoginAttempts != 7 {
		t.Errorf("FailedLoginAttempts: want 7, got %d", got.FailedLoginAttempts)
	}

	if got.LockedUntil == nil {
		t.Fatal("LockedUntil is nil, so IsLocked reports this locked account as unlocked")
	}
	if !got.LockedUntil.Equal(source.LockedUntil.Time) {
		t.Errorf("LockedUntil: want %v, got %v", source.LockedUntil.Time, *got.LockedUntil)
	}

	// The value above is a fixed past date, chosen so the sweep in this file
	// stays deterministic. IsLocked is time-relative, so it gets its own row
	// with a future lock — otherwise this test would assert that the column
	// arrives and never that arriving changes the answer.
	stillLocked := source
	stillLocked.LockedUntil = pgtype.Timestamptz{Time: time.Now().Add(time.Hour), Valid: true}
	if !userFromDB(stillLocked).IsLocked() {
		t.Error("a user whose locked_until is in the future must read as locked")
	}

	if got.LastFailedLogin == nil {
		t.Fatal("LastFailedLogin is nil")
	}
	if !got.LastFailedLogin.Equal(source.LastFailedLogin.Time) {
		t.Errorf("LastFailedLogin: want %v, got %v", source.LastFailedLogin.Time, *got.LastFailedLogin)
	}
}

// A NULL lockout column must arrive as nil rather than as a zero time, because
// IsLocked distinguishes the two and time.Time{} is in the past — an account
// that has never been locked and one whose lock expired must both read as
// unlocked, but only the first is nil.
func TestUserFromDBLeavesNullLockoutColumnsNil(t *testing.T) {
	source := fullyPopulatedDBUser()
	source.LockedUntil = pgtype.Timestamptz{}
	source.LastFailedLogin = pgtype.Timestamptz{}
	source.FailedLoginAttempts = 0

	got := userFromDB(source)

	if got.LockedUntil != nil {
		t.Errorf("a NULL locked_until must map to nil; got %v", *got.LockedUntil)
	}
	if got.LastFailedLogin != nil {
		t.Errorf("a NULL last_failed_login must map to nil; got %v", *got.LastFailedLogin)
	}
	if got.IsLocked() {
		t.Error("an account that has never been locked must not read as locked")
	}
}

// comparableFieldValue reduces a storage-layer value and its domain counterpart
// to a common shape so the two can be compared without the test knowing which
// convert.go helper each column happens to use.
func comparableFieldValue(v reflect.Value) any {
	switch value := v.Interface().(type) {
	case pgtype.UUID:
		return uuid.UUID(value.Bytes).String()
	case uuid.UUID:
		return value.String()
	case pgtype.Timestamptz:
		if !value.Valid {
			return nil
		}
		return value.Time.UTC()
	case time.Time:
		if value.IsZero() {
			return nil
		}
		return value.UTC()
	case *time.Time:
		if value == nil {
			return nil
		}
		return value.UTC()
	case []byte:
		return string(value)
	case db.UserRole:
		return string(value)
	case int32:
		return int64(value)
	case int:
		return int64(value)
	default:
		return value
	}
}
