// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blocked_slots.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBlockedSlot = `-- name: DeleteBlockedSlot :exec
DELETE FROM blocked_slots
WHERE id = $1
`

func (q *Queries) DeleteBlockedSlot(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBlockedSlot, id)
	return err
}

const getBlockedSlotByID = `-- name: GetBlockedSlotByID :one
SELECT id, court_id, date, start_time, end_time, reason, created_by, created_at, updated_at, span, complex_id FROM blocked_slots
WHERE id = $1
`

func (q *Queries) GetBlockedSlotByID(ctx context.Context, id pgtype.UUID) (BlockedSlot, error) {
	row := q.db.QueryRow(ctx, getBlockedSlotByID, id)
	var i BlockedSlot
	err := row.Scan(
		&i.ID,
		&i.CourtID,
		&i.Date,
		&i.StartTime,
		&i.EndTime,
		&i.Reason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Span,
		&i.ComplexID,
	)
	return i, err
}

const getBlockedSlots = `-- name: GetBlockedSlots :many
SELECT id, court_id, date, start_time, end_time, reason, created_by, created_at, updated_at, span, complex_id FROM blocked_slots
WHERE court_id = $1
  AND date BETWEEN $2 AND $3
ORDER BY date, start_time
`

type GetBlockedSlotsParams struct {
	CourtID pgtype.UUID `json:"court_id"`
	Date    pgtype.Date `json:"date"`
	Date_2  pgtype.Date `json:"date_2"`
}

func (q *Queries) GetBlockedSlots(ctx context.Context, arg GetBlockedSlotsParams) ([]BlockedSlot, error) {
	rows, err := q.db.Query(ctx, getBlockedSlots, arg.CourtID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlockedSlot
	for rows.Next() {
		var i BlockedSlot
		if err := rows.Scan(
			&i.ID,
			&i.CourtID,
			&i.Date,
			&i.StartTime,
			&i.EndTime,
			&i.Reason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Span,
			&i.ComplexID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
