// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBookedSlots = `-- name: GetBookedSlots :many
SELECT b.court_id, lower(b.span)::timestamptz AS starts_at, upper(b.span)::timestamptz AS ends_at
FROM bookings b
WHERE b.court_id = ANY($1::uuid[])
  AND b.span && local_day($2::date)
  AND b.status NOT IN ('cancelled', 'no_show')
  AND NOT (
    b.status = 'pending'
    AND b.collection_status = 'unpaid'
    AND b.created_by IS NULL
    AND b.created_at < NOW() - make_interval(secs => $3::float8)
  )
ORDER BY b.court_id, lower(b.span)
`

type GetBookedSlotsParams struct {
	Column1              []pgtype.UUID `json:"column_1"`
	Day                  pgtype.Date   `json:"day"`
	PaymentExpirySeconds float64       `json:"payment_expiry_seconds"`
}

type GetBookedSlotsRow struct {
	CourtID  pgtype.UUID        `json:"court_id"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
	EndsAt   pgtype.Timestamptz `json:"ends_at"`
}

// GetBookedSlots returns the hours already taken on the given courts and date.
//
// Its status predicate must stay identical to releasedBookingStatuses in
// internal/data/slotguard and to the WHERE clause on
// bookings_no_overlapping_span (db/migrations/001_init.sql). Those three are one
// predicate written three times, because a constraint inside Postgres cannot
// read a Go constant and a file compiled by sqlc cannot concatenate one.
// History for why the count matters: this query was named GetAvailableSlots and
// excluded only 'cancelled' while slotTaken excluded 'cancelled' and 'no_show',
// so a no_show slot was drawn as taken, passed the overlap check as free, and
// was refused by the index as a duplicate — three answers to one question.
//
// The fourth copy, idx_bookings_no_double, is gone: the exclusion constraint dropped
// it once the exclusion constraint made it redundant.
// Two instants, not a date and two times of day. A booking that runs past
// midnight has no single time of day that says which day its end belongs to,
// and the caller comparing "23:00" against "01:00" lexicographically is exactly
// the shape that made a 23:00 booking invisible to the guard meant to see it
// (the retired CHECK (start_time < end_time)). lower/upper come off the same span the exclusion
// constraint enforces, so what the storefront greys out and what the write path
// refuses are read from one value.
//
// Matching on `span && local_day(day)` rather than `date = day`: a court
// occupied until 01:00 is occupied on that morning's grid too. See
// local_day() in db/migrations/001_init.sql for why "occupies day X" beat "started on day X".
//
// payment_expiry_seconds is the configured payment hold (Config.PaymentExpiry,
// default 15 minutes — see internal/stores), passed as a parameter
// rather than baked in as INTERVAL '15 minutes' for the same reason slotTaken
// in internal/data/slotguard takes hold as an argument: this carve-out and
// the insert-time collision guard have to agree on the same number, or a
// pending booking between the two configured values shows as free here and
// taken there (or the reverse). Both now read Config.PaymentExpiry once.
func (q *Queries) GetBookedSlots(ctx context.Context, arg GetBookedSlotsParams) ([]GetBookedSlotsRow, error) {
	rows, err := q.db.Query(ctx, getBookedSlots, arg.Column1, arg.Day, arg.PaymentExpirySeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBookedSlotsRow
	for rows.Next() {
		var i GetBookedSlotsRow
		if err := rows.Scan(&i.CourtID, &i.StartsAt, &i.EndsAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT id, complex_id, court_id, client_id, date, start_time, duration_minutes, price, deposit_amount, status, reminder_sent_2h, notes, created_by, created_at, updated_at, refund_intent_at, span, collection_status, refund_status FROM bookings
WHERE id = $1
  AND ($2::uuid IS NULL
       OR complex_id = $2::uuid)
`

type GetBookingByIDParams struct {
	ID        pgtype.UUID `json:"id"`
	ComplexID pgtype.UUID `json:"complex_id"`
}

// The tenant predicate is the explicit half of the isolation the row-level
// security policies enforce (db/migrations/001_init.sql). RLS is the guarantee;
// this is the statement saying out loud which tenant the row is supposed to
// belong to, so a lookup by id cannot reach across tenants even if a policy is
// ever relaxed, dropped, or bypassed for a path that did not need the bypass.
//
// It is optional, and the NULL branch is not a loophole: it is exactly the set
// of callers that legitimately have no tenant on the context — the cron sweeps,
// the superadmin console, the MercadoPago webhook resolving its payment, the
// public link resolving its booking. Those run under app.bypass_tenant, so RLS
// lets them through anyway and a mandatory predicate here would only break
// them. The store passes data.TenantFromContext's answer; a scoped caller gets
// the filter, a bypassed one is exactly where it was.
func (q *Queries) GetBookingByID(ctx context.Context, arg GetBookingByIDParams) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByID, arg.ID, arg.ComplexID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.ComplexID,
		&i.CourtID,
		&i.ClientID,
		&i.Date,
		&i.StartTime,
		&i.DurationMinutes,
		&i.Price,
		&i.DepositAmount,
		&i.Status,
		&i.ReminderSent2h,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RefundIntentAt,
		&i.Span,
		&i.CollectionStatus,
		&i.RefundStatus,
	)
	return i, err
}

const getBookingByIDForUpdate = `-- name: GetBookingByIDForUpdate :one
SELECT id, complex_id, court_id, client_id, date, start_time, duration_minutes, price, deposit_amount, status, reminder_sent_2h, notes, created_by, created_at, updated_at, refund_intent_at, span, collection_status, refund_status FROM bookings
WHERE id = $1
  AND ($2::uuid IS NULL
       OR complex_id = $2::uuid)
FOR UPDATE
`

type GetBookingByIDForUpdateParams struct {
	ID        pgtype.UUID `json:"id"`
	ComplexID pgtype.UUID `json:"complex_id"`
}

// Locks the booking row for the duration of the enclosing transaction.
// The refund recorder reads status, notes and deposit_amount back under this
// lock and writes them straight through, so a concurrent booking update cannot
// interleave with the money write or erase the deposit. This row lock is the
// serialization on this table now that the `version` counter is gone: it is
// held by the database for the whole transaction, which is what the counter
// only pretended to be.
//
// Tenant-scoped like GetBookingByID above, and optional for the same reason.
func (q *Queries) GetBookingByIDForUpdate(ctx context.Context, arg GetBookingByIDForUpdateParams) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByIDForUpdate, arg.ID, arg.ComplexID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.ComplexID,
		&i.CourtID,
		&i.ClientID,
		&i.Date,
		&i.StartTime,
		&i.DurationMinutes,
		&i.Price,
		&i.DepositAmount,
		&i.Status,
		&i.ReminderSent2h,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RefundIntentAt,
		&i.Span,
		&i.CollectionStatus,
		&i.RefundStatus,
	)
	return i, err
}

const getBookingsByComplex = `-- name: GetBookingsByComplex :many
SELECT id, complex_id, court_id, client_id, date, start_time, duration_minutes, price, deposit_amount, status, reminder_sent_2h, notes, created_by, created_at, updated_at, refund_intent_at, span, collection_status, refund_status FROM bookings
WHERE complex_id = $1
  AND date BETWEEN $2 AND $3
  AND (date, id) > ($4, $5)
ORDER BY date ASC, id ASC
LIMIT $6
`

type GetBookingsByComplexParams struct {
	ComplexID pgtype.UUID `json:"complex_id"`
	Date      pgtype.Date `json:"date"`
	Date_2    pgtype.Date `json:"date_2"`
	Date_3    pgtype.Date `json:"date_3"`
	Date_4    pgtype.Date `json:"date_4"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) GetBookingsByComplex(ctx context.Context, arg GetBookingsByComplexParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, getBookingsByComplex,
		arg.ComplexID,
		arg.Date,
		arg.Date_2,
		arg.Date_3,
		arg.Date_4,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.ComplexID,
			&i.CourtID,
			&i.ClientID,
			&i.Date,
			&i.StartTime,
			&i.DurationMinutes,
			&i.Price,
			&i.DepositAmount,
			&i.Status,
			&i.ReminderSent2h,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RefundIntentAt,
			&i.Span,
			&i.CollectionStatus,
			&i.RefundStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookingsByCourt = `-- name: GetBookingsByCourt :many
SELECT id, complex_id, court_id, client_id, date, start_time, duration_minutes, price, deposit_amount, status, reminder_sent_2h, notes, created_by, created_at, updated_at, refund_intent_at, span, collection_status, refund_status FROM bookings
WHERE court_id = $1
  AND date BETWEEN $2 AND $3
ORDER BY date ASC, start_time ASC
`

type GetBookingsByCourtParams struct {
	CourtID pgtype.UUID `json:"court_id"`
	Date    pgtype.Date `json:"date"`
	Date_2  pgtype.Date `json:"date_2"`
}

func (q *Queries) GetBookingsByCourt(ctx context.Context, arg GetBookingsByCourtParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, getBookingsByCourt, arg.CourtID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.ComplexID,
			&i.CourtID,
			&i.ClientID,
			&i.Date,
			&i.StartTime,
			&i.DurationMinutes,
			&i.Price,
			&i.DepositAmount,
			&i.Status,
			&i.ReminderSent2h,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RefundIntentAt,
			&i.Span,
			&i.CollectionStatus,
			&i.RefundStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookingsForReminder2h = `-- name: GetBookingsForReminder2h :many
SELECT id, complex_id, court_id, client_id, date, start_time, duration_minutes, price, deposit_amount, status, reminder_sent_2h, notes, created_by, created_at, updated_at, refund_intent_at, span, collection_status, refund_status FROM bookings
WHERE booking_starts_at(date, start_time) > $1::timestamptz
  AND booking_starts_at(date, start_time) <= $1::timestamptz + INTERVAL '2 hours'
  AND status = 'confirmed'
  AND reminder_sent_2h = false
`

// GetBookingsForReminder2h returns the confirmed bookings whose game starts
// within the next two hours and that have not been reminded yet.
//
// The window is expressed over booking_starts_at (db/migrations/001_init.sql), the one
// place date and start_time are combined into an instant, and must stay that
// way: the predicate this replaced compared times of day
// (`start_time <= (now::time + INTERVAL '2 hours')`), which wraps at 23:00 into
// `start_time <= 01:00 AND start_time > 23:00` and selects nothing, so no
// booking in the last two hours of the day was ever reminded. Two timestamptz
// values have no midnight between them.
//
// `now` is a parameter rather than NOW() so the caller owns the clock — the
// same reason GetForReminder2hEnriched in internal/bookings/store/bookings.go takes one.
// A window keyed to whenever the test suite happened to run is a window nobody
// can test at 23:00.
func (q *Queries) GetBookingsForReminder2h(ctx context.Context, now pgtype.Timestamptz) ([]Booking, error) {
	rows, err := q.db.Query(ctx, getBookingsForReminder2h, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.ComplexID,
			&i.CourtID,
			&i.ClientID,
			&i.Date,
			&i.StartTime,
			&i.DurationMinutes,
			&i.Price,
			&i.DepositAmount,
			&i.Status,
			&i.ReminderSent2h,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RefundIntentAt,
			&i.Span,
			&i.CollectionStatus,
			&i.RefundStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNextBookingByClientPhone = `-- name: GetNextBookingByClientPhone :one
SELECT id, complex_id, court_id, client_id, date, start_time, duration_minutes, price, deposit_amount, status, reminder_sent_2h, notes, created_by, created_at, updated_at, refund_intent_at, span, collection_status, refund_status FROM bookings WHERE false LIMIT 1
`

// Kept for backwards compatibility with generated code. No longer used by business logic.
func (q *Queries) GetNextBookingByClientPhone(ctx context.Context) (Booking, error) {
	row := q.db.QueryRow(ctx, getNextBookingByClientPhone)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.ComplexID,
		&i.CourtID,
		&i.ClientID,
		&i.Date,
		&i.StartTime,
		&i.DurationMinutes,
		&i.Price,
		&i.DepositAmount,
		&i.Status,
		&i.ReminderSent2h,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RefundIntentAt,
		&i.Span,
		&i.CollectionStatus,
		&i.RefundStatus,
	)
	return i, err
}

const getUnconfirmedAfterReminder = `-- name: GetUnconfirmedAfterReminder :many
SELECT id, complex_id, court_id, client_id, date, start_time, duration_minutes, price, deposit_amount, status, reminder_sent_2h, notes, created_by, created_at, updated_at, refund_intent_at, span, collection_status, refund_status FROM bookings WHERE false
`

// Kept for backwards compatibility with generated code. No longer used by business logic.
func (q *Queries) GetUnconfirmedAfterReminder(ctx context.Context) ([]Booking, error) {
	rows, err := q.db.Query(ctx, getUnconfirmedAfterReminder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.ComplexID,
			&i.CourtID,
			&i.ClientID,
			&i.Date,
			&i.StartTime,
			&i.DurationMinutes,
			&i.Price,
			&i.DepositAmount,
			&i.Status,
			&i.ReminderSent2h,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RefundIntentAt,
			&i.Span,
			&i.CollectionStatus,
			&i.RefundStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBooking = `-- name: InsertBooking :one
INSERT INTO bookings (
    complex_id, court_id, client_id, date,
    start_time, duration_minutes,
    price, deposit_amount, status, collection_status, refund_status,
    notes, created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, complex_id, court_id, client_id, date, start_time, duration_minutes, price, deposit_amount, status, reminder_sent_2h, notes, created_by, created_at, updated_at, refund_intent_at, span, collection_status, refund_status
`

type InsertBookingParams struct {
	ComplexID        pgtype.UUID   `json:"complex_id"`
	CourtID          pgtype.UUID   `json:"court_id"`
	ClientID         pgtype.UUID   `json:"client_id"`
	Date             pgtype.Date   `json:"date"`
	StartTime        pgtype.Time   `json:"start_time"`
	DurationMinutes  int32         `json:"duration_minutes"`
	Price            int32         `json:"price"`
	DepositAmount    int32         `json:"deposit_amount"`
	Status           BookingStatus `json:"status"`
	CollectionStatus string        `json:"collection_status"`
	RefundStatus     string        `json:"refund_status"`
	Notes            pgtype.Text   `json:"notes"`
	CreatedBy        pgtype.UUID   `json:"created_by"`
}

func (q *Queries) InsertBooking(ctx context.Context, arg InsertBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, insertBooking,
		arg.ComplexID,
		arg.CourtID,
		arg.ClientID,
		arg.Date,
		arg.StartTime,
		arg.DurationMinutes,
		arg.Price,
		arg.DepositAmount,
		arg.Status,
		arg.CollectionStatus,
		arg.RefundStatus,
		arg.Notes,
		arg.CreatedBy,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.ComplexID,
		&i.CourtID,
		&i.ClientID,
		&i.Date,
		&i.StartTime,
		&i.DurationMinutes,
		&i.Price,
		&i.DepositAmount,
		&i.Status,
		&i.ReminderSent2h,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RefundIntentAt,
		&i.Span,
		&i.CollectionStatus,
		&i.RefundStatus,
	)
	return i, err
}

const markReminderSent2h = `-- name: MarkReminderSent2h :exec
UPDATE bookings
SET reminder_sent_2h = true, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkReminderSent2h(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markReminderSent2h, id)
	return err
}

const updateBooking = `-- name: UpdateBooking :one
UPDATE bookings
SET status = $2,
    collection_status = $3,
    refund_status = $4,
    notes = $5,
    deposit_amount = $6,
    refund_intent_at = $7
WHERE id = $1
RETURNING id, complex_id, court_id, client_id, date, start_time, duration_minutes, price, deposit_amount, status, reminder_sent_2h, notes, created_by, created_at, updated_at, refund_intent_at, span, collection_status, refund_status
`

type UpdateBookingParams struct {
	ID               pgtype.UUID        `json:"id"`
	Status           BookingStatus      `json:"status"`
	CollectionStatus string             `json:"collection_status"`
	RefundStatus     string             `json:"refund_status"`
	Notes            pgtype.Text        `json:"notes"`
	DepositAmount    int32              `json:"deposit_amount"`
	RefundIntentAt   pgtype.Timestamptz `json:"refund_intent_at"`
}

// Unconditional on the row's prior state. What refuses an illegitimate write is
// the bookings_forbid_status_reversal trigger, which is enforced for every
// writer rather than for the one query that remembered to check a counter —
// see the bookings section of db/migrations/001_init.sql for why the counter was removed.
func (q *Queries) UpdateBooking(ctx context.Context, arg UpdateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, updateBooking,
		arg.ID,
		arg.Status,
		arg.CollectionStatus,
		arg.RefundStatus,
		arg.Notes,
		arg.DepositAmount,
		arg.RefundIntentAt,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.ComplexID,
		&i.CourtID,
		&i.ClientID,
		&i.Date,
		&i.StartTime,
		&i.DurationMinutes,
		&i.Price,
		&i.DepositAmount,
		&i.Status,
		&i.ReminderSent2h,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RefundIntentAt,
		&i.Span,
		&i.CollectionStatus,
		&i.RefundStatus,
	)
	return i, err
}
