// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cashbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeCashSession = `-- name: CloseCashSession :one
UPDATE cash_sessions
SET closed_at = NOW(), closed_by = $1, counted_cash = $2, expected_cash = $3, closing_note = $4
WHERE id = $5 AND complex_id = $6
RETURNING id, complex_id, opened_at, opened_by, opening_cash, closed_at, closed_by, counted_cash, expected_cash, difference, opening_note, closing_note, created_at, updated_at
`

type CloseCashSessionParams struct {
	ClosedBy     pgtype.UUID `json:"closed_by"`
	CountedCash  pgtype.Int4 `json:"counted_cash"`
	ExpectedCash pgtype.Int4 `json:"expected_cash"`
	ClosingNote  pgtype.Text `json:"closing_note"`
	ID           pgtype.UUID `json:"id"`
	ComplexID    pgtype.UUID `json:"complex_id"`
}

// closing_note is its own column: it never touches opening_note, so a
// closing note can never erase what Open recorded.
func (q *Queries) CloseCashSession(ctx context.Context, arg CloseCashSessionParams) (CashSession, error) {
	row := q.db.QueryRow(ctx, closeCashSession,
		arg.ClosedBy,
		arg.CountedCash,
		arg.ExpectedCash,
		arg.ClosingNote,
		arg.ID,
		arg.ComplexID,
	)
	var i CashSession
	err := row.Scan(
		&i.ID,
		&i.ComplexID,
		&i.OpenedAt,
		&i.OpenedBy,
		&i.OpeningCash,
		&i.ClosedAt,
		&i.ClosedBy,
		&i.CountedCash,
		&i.ExpectedCash,
		&i.Difference,
		&i.OpeningNote,
		&i.ClosingNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCashMovementByID = `-- name: GetCashMovementByID :one
SELECT id, complex_id, session_id, kind, category, method, amount, note, voids_movement_id, created_at, created_by FROM cash_movements
WHERE id = $1 AND complex_id = $2
`

type GetCashMovementByIDParams struct {
	ID        pgtype.UUID `json:"id"`
	ComplexID pgtype.UUID `json:"complex_id"`
}

func (q *Queries) GetCashMovementByID(ctx context.Context, arg GetCashMovementByIDParams) (CashMovement, error) {
	row := q.db.QueryRow(ctx, getCashMovementByID, arg.ID, arg.ComplexID)
	var i CashMovement
	err := row.Scan(
		&i.ID,
		&i.ComplexID,
		&i.SessionID,
		&i.Kind,
		&i.Category,
		&i.Method,
		&i.Amount,
		&i.Note,
		&i.VoidsMovementID,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getCashSessionByID = `-- name: GetCashSessionByID :one
SELECT id, complex_id, opened_at, opened_by, opening_cash, closed_at, closed_by, counted_cash, expected_cash, difference, opening_note, closing_note, created_at, updated_at FROM cash_sessions
WHERE id = $1 AND complex_id = $2
`

type GetCashSessionByIDParams struct {
	ID        pgtype.UUID `json:"id"`
	ComplexID pgtype.UUID `json:"complex_id"`
}

func (q *Queries) GetCashSessionByID(ctx context.Context, arg GetCashSessionByIDParams) (CashSession, error) {
	row := q.db.QueryRow(ctx, getCashSessionByID, arg.ID, arg.ComplexID)
	var i CashSession
	err := row.Scan(
		&i.ID,
		&i.ComplexID,
		&i.OpenedAt,
		&i.OpenedBy,
		&i.OpeningCash,
		&i.ClosedAt,
		&i.ClosedBy,
		&i.CountedCash,
		&i.ExpectedCash,
		&i.Difference,
		&i.OpeningNote,
		&i.ClosingNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCashSessionByIDForUpdate = `-- name: GetCashSessionByIDForUpdate :one
SELECT id, complex_id, opened_at, opened_by, opening_cash, closed_at, closed_by, counted_cash, expected_cash, difference, opening_note, closing_note, created_at, updated_at FROM cash_sessions
WHERE id = $1 AND complex_id = $2
FOR UPDATE
`

type GetCashSessionByIDForUpdateParams struct {
	ID        pgtype.UUID `json:"id"`
	ComplexID pgtype.UUID `json:"complex_id"`
}

// Every write against a session (a movement, a void, the close itself) takes
// this lock first, in the same transaction as the write, so a movement
// cannot land in a session that is being closed concurrently and a session
// cannot be closed twice.
func (q *Queries) GetCashSessionByIDForUpdate(ctx context.Context, arg GetCashSessionByIDForUpdateParams) (CashSession, error) {
	row := q.db.QueryRow(ctx, getCashSessionByIDForUpdate, arg.ID, arg.ComplexID)
	var i CashSession
	err := row.Scan(
		&i.ID,
		&i.ComplexID,
		&i.OpenedAt,
		&i.OpenedBy,
		&i.OpeningCash,
		&i.ClosedAt,
		&i.ClosedBy,
		&i.CountedCash,
		&i.ExpectedCash,
		&i.Difference,
		&i.OpeningNote,
		&i.ClosingNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOpenCashSessionByComplex = `-- name: GetOpenCashSessionByComplex :one
SELECT id, complex_id, opened_at, opened_by, opening_cash, closed_at, closed_by, counted_cash, expected_cash, difference, opening_note, closing_note, created_at, updated_at FROM cash_sessions
WHERE complex_id = $1 AND closed_at IS NULL
`

// The read-only "current session" lookup — GET /current — never locks.
func (q *Queries) GetOpenCashSessionByComplex(ctx context.Context, complexID pgtype.UUID) (CashSession, error) {
	row := q.db.QueryRow(ctx, getOpenCashSessionByComplex, complexID)
	var i CashSession
	err := row.Scan(
		&i.ID,
		&i.ComplexID,
		&i.OpenedAt,
		&i.OpenedBy,
		&i.OpeningCash,
		&i.ClosedAt,
		&i.ClosedBy,
		&i.CountedCash,
		&i.ExpectedCash,
		&i.Difference,
		&i.OpeningNote,
		&i.ClosingNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOpenCashSessionForUpdate = `-- name: GetOpenCashSessionForUpdate :one
SELECT id, complex_id, opened_at, opened_by, opening_cash, closed_at, closed_by, counted_cash, expected_cash, difference, opening_note, closing_note, created_at, updated_at FROM cash_sessions
WHERE complex_id = $1 AND closed_at IS NULL
FOR UPDATE
`

// Locks the row (if any) so a second open cannot race the check-then-insert:
// the caller still relies on idx_cash_sessions_one_open for the actual
// guarantee (this SELECT can only lock a row that already committed), but
// taking the lock here means a concurrent close sees this transaction's
// intent before either commits.
func (q *Queries) GetOpenCashSessionForUpdate(ctx context.Context, complexID pgtype.UUID) (CashSession, error) {
	row := q.db.QueryRow(ctx, getOpenCashSessionForUpdate, complexID)
	var i CashSession
	err := row.Scan(
		&i.ID,
		&i.ComplexID,
		&i.OpenedAt,
		&i.OpenedBy,
		&i.OpeningCash,
		&i.ClosedAt,
		&i.ClosedBy,
		&i.CountedCash,
		&i.ExpectedCash,
		&i.Difference,
		&i.OpeningNote,
		&i.ClosingNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCashMovement = `-- name: InsertCashMovement :one
INSERT INTO cash_movements (complex_id, session_id, kind, category, method, amount, note, voids_movement_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, complex_id, session_id, kind, category, method, amount, note, voids_movement_id, created_at, created_by
`

type InsertCashMovementParams struct {
	ComplexID       pgtype.UUID   `json:"complex_id"`
	SessionID       pgtype.UUID   `json:"session_id"`
	Kind            string        `json:"kind"`
	Category        string        `json:"category"`
	Method          PaymentMethod `json:"method"`
	Amount          int32         `json:"amount"`
	Note            pgtype.Text   `json:"note"`
	VoidsMovementID pgtype.UUID   `json:"voids_movement_id"`
	CreatedBy       pgtype.UUID   `json:"created_by"`
}

// Serves both an ordinary movement (voids_movement_id NULL) and a void
// (voids_movement_id set): cash_movements_check_void (003_cashbox.sql)
// enforces every void invariant that needs to read the original row, so this
// query is deliberately the same one call for both.
func (q *Queries) InsertCashMovement(ctx context.Context, arg InsertCashMovementParams) (CashMovement, error) {
	row := q.db.QueryRow(ctx, insertCashMovement,
		arg.ComplexID,
		arg.SessionID,
		arg.Kind,
		arg.Category,
		arg.Method,
		arg.Amount,
		arg.Note,
		arg.VoidsMovementID,
		arg.CreatedBy,
	)
	var i CashMovement
	err := row.Scan(
		&i.ID,
		&i.ComplexID,
		&i.SessionID,
		&i.Kind,
		&i.Category,
		&i.Method,
		&i.Amount,
		&i.Note,
		&i.VoidsMovementID,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const insertCashSession = `-- name: InsertCashSession :one
INSERT INTO cash_sessions (complex_id, opened_by, opening_cash, opening_note)
VALUES ($1, $2, $3, $4)
RETURNING id, complex_id, opened_at, opened_by, opening_cash, closed_at, closed_by, counted_cash, expected_cash, difference, opening_note, closing_note, created_at, updated_at
`

type InsertCashSessionParams struct {
	ComplexID   pgtype.UUID `json:"complex_id"`
	OpenedBy    pgtype.UUID `json:"opened_by"`
	OpeningCash int32       `json:"opening_cash"`
	OpeningNote pgtype.Text `json:"opening_note"`
}

func (q *Queries) InsertCashSession(ctx context.Context, arg InsertCashSessionParams) (CashSession, error) {
	row := q.db.QueryRow(ctx, insertCashSession,
		arg.ComplexID,
		arg.OpenedBy,
		arg.OpeningCash,
		arg.OpeningNote,
	)
	var i CashSession
	err := row.Scan(
		&i.ID,
		&i.ComplexID,
		&i.OpenedAt,
		&i.OpenedBy,
		&i.OpeningCash,
		&i.ClosedAt,
		&i.ClosedBy,
		&i.CountedCash,
		&i.ExpectedCash,
		&i.Difference,
		&i.OpeningNote,
		&i.ClosingNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCashMovementsBySession = `-- name: ListCashMovementsBySession :many
SELECT id, complex_id, session_id, kind, category, method, amount, note, voids_movement_id, created_at, created_by FROM cash_movements
WHERE session_id = $1 AND complex_id = $2
ORDER BY created_at ASC, id ASC
`

type ListCashMovementsBySessionParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	ComplexID pgtype.UUID `json:"complex_id"`
}

// Oldest first: a session's ledger reads top to bottom like a receipt tape.
// Not paginated — a shift's movement count is bounded by a business day at
// the counter, the same reasoning ListBlockedSlots' unpaginated call applies.
func (q *Queries) ListCashMovementsBySession(ctx context.Context, arg ListCashMovementsBySessionParams) ([]CashMovement, error) {
	rows, err := q.db.Query(ctx, listCashMovementsBySession, arg.SessionID, arg.ComplexID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CashMovement
	for rows.Next() {
		var i CashMovement
		if err := rows.Scan(
			&i.ID,
			&i.ComplexID,
			&i.SessionID,
			&i.Kind,
			&i.Category,
			&i.Method,
			&i.Amount,
			&i.Note,
			&i.VoidsMovementID,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCashSessionsByComplex = `-- name: ListCashSessionsByComplex :many
SELECT id, complex_id, opened_at, opened_by, opening_cash, closed_at, closed_by, counted_cash, expected_cash, difference, opening_note, closing_note, created_at, updated_at FROM cash_sessions
WHERE complex_id = $1
  AND (NOT $2::bool
       OR (opened_at, id) < ($3::timestamptz, $4::uuid))
ORDER BY opened_at DESC, id DESC
LIMIT $5::int
`

type ListCashSessionsByComplexParams struct {
	ComplexID      pgtype.UUID        `json:"complex_id"`
	HasCursor      bool               `json:"has_cursor"`
	CursorOpenedAt pgtype.Timestamptz `json:"cursor_opened_at"`
	CursorID       pgtype.UUID        `json:"cursor_id"`
	PageLimit      int32              `json:"page_limit"`
}

// Keyset pagination, same shape as audit_log's listAuditLogsSQL: has_cursor
// is false on the first page, so the OR's left side short-circuits instead of
// comparing against a zero-value timestamp.
func (q *Queries) ListCashSessionsByComplex(ctx context.Context, arg ListCashSessionsByComplexParams) ([]CashSession, error) {
	rows, err := q.db.Query(ctx, listCashSessionsByComplex,
		arg.ComplexID,
		arg.HasCursor,
		arg.CursorOpenedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CashSession
	for rows.Next() {
		var i CashSession
		if err := rows.Scan(
			&i.ID,
			&i.ComplexID,
			&i.OpenedAt,
			&i.OpenedBy,
			&i.OpeningCash,
			&i.ClosedAt,
			&i.ClosedBy,
			&i.CountedCash,
			&i.ExpectedCash,
			&i.Difference,
			&i.OpeningNote,
			&i.ClosingNote,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumCashMovementsBySession = `-- name: SumCashMovementsBySession :many
SELECT method::text, kind, category, COALESCE(SUM(amount), 0)::bigint AS total, COUNT(*)::int AS count
FROM cash_movements
WHERE session_id = $1 AND complex_id = $2
GROUP BY method, kind, category
`

type SumCashMovementsBySessionParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	ComplexID pgtype.UUID `json:"complex_id"`
}

type SumCashMovementsBySessionRow struct {
	Method   string `json:"method"`
	Kind     string `json:"kind"`
	Category string `json:"category"`
	Total    int64  `json:"total"`
	Count    int32  `json:"count"`
}

// One row per (method, kind, category) combination actually used in the
// session. The service derives two different things from this same result:
// the summary's full breakdown (every row, every method), and the cash
// reconciliation's own income/expense totals (the rows whose method is
// 'cash' — "Cash reconciliation counts only cash" is a Go-side filter over
// this query's rows, not a WHERE clause here, because the summary needs the
// other methods' rows too).
func (q *Queries) SumCashMovementsBySession(ctx context.Context, arg SumCashMovementsBySessionParams) ([]SumCashMovementsBySessionRow, error) {
	rows, err := q.db.Query(ctx, sumCashMovementsBySession, arg.SessionID, arg.ComplexID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumCashMovementsBySessionRow
	for rows.Next() {
		var i SumCashMovementsBySessionRow
		if err := rows.Scan(
			&i.Method,
			&i.Kind,
			&i.Category,
			&i.Total,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
