// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clients.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getClientByID = `-- name: GetClientByID :one
SELECT
  c.id, c.complex_id, c.first_name, c.last_name, c.phone, c.email, c.notes,
  c.is_blocked, c.no_shows, c.created_at, c.updated_at,
  COALESCE((
    SELECT COUNT(*)::int FROM bookings b
    WHERE b.client_id = c.id AND b.status IN ('confirmed', 'completed', 'no_show')
  ), 0)::int AS total_bookings
FROM clients c
WHERE c.id = $1
  AND ($2::uuid IS NULL
       OR c.complex_id = $2::uuid)
`

type GetClientByIDParams struct {
	ID        pgtype.UUID `json:"id"`
	ComplexID pgtype.UUID `json:"complex_id"`
}

type GetClientByIDRow struct {
	ID            pgtype.UUID        `json:"id"`
	ComplexID     pgtype.UUID        `json:"complex_id"`
	FirstName     string             `json:"first_name"`
	LastName      string             `json:"last_name"`
	Phone         string             `json:"phone"`
	Email         pgtype.Text        `json:"email"`
	Notes         pgtype.Text        `json:"notes"`
	IsBlocked     bool               `json:"is_blocked"`
	NoShows       int32              `json:"no_shows"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	TotalBookings int32              `json:"total_bookings"`
}

// Tenant-scoped: see the note on GetBookingByID in bookings.sql for why the
// predicate is optional.
func (q *Queries) GetClientByID(ctx context.Context, arg GetClientByIDParams) (GetClientByIDRow, error) {
	row := q.db.QueryRow(ctx, getClientByID, arg.ID, arg.ComplexID)
	var i GetClientByIDRow
	err := row.Scan(
		&i.ID,
		&i.ComplexID,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Email,
		&i.Notes,
		&i.IsBlocked,
		&i.NoShows,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotalBookings,
	)
	return i, err
}

const getClientByPhone = `-- name: GetClientByPhone :one
SELECT
  c.id, c.complex_id, c.first_name, c.last_name, c.phone, c.email, c.notes,
  c.is_blocked, c.no_shows, c.created_at, c.updated_at,
  COALESCE((
    SELECT COUNT(*)::int FROM bookings b
    WHERE b.client_id = c.id AND b.status IN ('confirmed', 'completed', 'no_show')
  ), 0)::int AS total_bookings
FROM clients c
WHERE c.complex_id = $1
  AND c.phone = $2
`

type GetClientByPhoneParams struct {
	ComplexID pgtype.UUID `json:"complex_id"`
	Phone     string      `json:"phone"`
}

type GetClientByPhoneRow struct {
	ID            pgtype.UUID        `json:"id"`
	ComplexID     pgtype.UUID        `json:"complex_id"`
	FirstName     string             `json:"first_name"`
	LastName      string             `json:"last_name"`
	Phone         string             `json:"phone"`
	Email         pgtype.Text        `json:"email"`
	Notes         pgtype.Text        `json:"notes"`
	IsBlocked     bool               `json:"is_blocked"`
	NoShows       int32              `json:"no_shows"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	TotalBookings int32              `json:"total_bookings"`
}

func (q *Queries) GetClientByPhone(ctx context.Context, arg GetClientByPhoneParams) (GetClientByPhoneRow, error) {
	row := q.db.QueryRow(ctx, getClientByPhone, arg.ComplexID, arg.Phone)
	var i GetClientByPhoneRow
	err := row.Scan(
		&i.ID,
		&i.ComplexID,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Email,
		&i.Notes,
		&i.IsBlocked,
		&i.NoShows,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotalBookings,
	)
	return i, err
}

const getClientsByComplex = `-- name: GetClientsByComplex :many
SELECT id, complex_id, first_name, last_name, phone, email, notes, is_blocked, total_bookings, no_shows, created_at, updated_at FROM clients
WHERE complex_id = $1
  AND (created_at, id) > ($2, $3)
ORDER BY created_at ASC, id ASC
LIMIT $4
`

type GetClientsByComplexParams struct {
	ComplexID   pgtype.UUID        `json:"complex_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
	Limit       int32              `json:"limit"`
}

func (q *Queries) GetClientsByComplex(ctx context.Context, arg GetClientsByComplexParams) ([]Client, error) {
	rows, err := q.db.Query(ctx, getClientsByComplex,
		arg.ComplexID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.ComplexID,
			&i.FirstName,
			&i.LastName,
			&i.Phone,
			&i.Email,
			&i.Notes,
			&i.IsBlocked,
			&i.TotalBookings,
			&i.NoShows,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementNoShowCount = `-- name: IncrementNoShowCount :exec
UPDATE clients
SET no_shows = no_shows + 1
WHERE id = $1
`

func (q *Queries) IncrementNoShowCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementNoShowCount, id)
	return err
}

const insertClient = `-- name: InsertClient :one
INSERT INTO clients (complex_id, first_name, last_name, phone, email, notes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, complex_id, first_name, last_name, phone, email, notes, is_blocked, total_bookings, no_shows, created_at, updated_at
`

type InsertClientParams struct {
	ComplexID pgtype.UUID `json:"complex_id"`
	FirstName string      `json:"first_name"`
	LastName  string      `json:"last_name"`
	Phone     string      `json:"phone"`
	Email     pgtype.Text `json:"email"`
	Notes     pgtype.Text `json:"notes"`
}

func (q *Queries) InsertClient(ctx context.Context, arg InsertClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, insertClient,
		arg.ComplexID,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.Email,
		arg.Notes,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.ComplexID,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Email,
		&i.Notes,
		&i.IsBlocked,
		&i.TotalBookings,
		&i.NoShows,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients
SET first_name = $1,
    last_name = $2,
    phone = $3,
    email = $4,
    notes = $5,
    is_blocked = $6
WHERE id = $7
RETURNING id, complex_id, first_name, last_name, phone, email, notes, is_blocked, total_bookings, no_shows, created_at, updated_at
`

type UpdateClientParams struct {
	FirstName string      `json:"first_name"`
	LastName  string      `json:"last_name"`
	Phone     string      `json:"phone"`
	Email     pgtype.Text `json:"email"`
	Notes     pgtype.Text `json:"notes"`
	IsBlocked bool        `json:"is_blocked"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClient,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.Email,
		arg.Notes,
		arg.IsBlocked,
		arg.ID,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.ComplexID,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Email,
		&i.Notes,
		&i.IsBlocked,
		&i.TotalBookings,
		&i.NoShows,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
