// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: complex_schedules.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSchedulesByComplex = `-- name: GetSchedulesByComplex :many
SELECT id, complex_id, day, open_time, close_time, is_closed, created_at, updated_at FROM complex_schedules
WHERE complex_id = $1
ORDER BY day
`

func (q *Queries) GetSchedulesByComplex(ctx context.Context, complexID pgtype.UUID) ([]ComplexSchedule, error) {
	rows, err := q.db.Query(ctx, getSchedulesByComplex, complexID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComplexSchedule
	for rows.Next() {
		var i ComplexSchedule
		if err := rows.Scan(
			&i.ID,
			&i.ComplexID,
			&i.Day,
			&i.OpenTime,
			&i.CloseTime,
			&i.IsClosed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSchedule = `-- name: UpsertSchedule :one
INSERT INTO complex_schedules (complex_id, day, open_time, close_time, is_closed)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (complex_id, day)
DO UPDATE SET
    open_time = EXCLUDED.open_time,
    close_time = EXCLUDED.close_time,
    is_closed = EXCLUDED.is_closed
RETURNING id, complex_id, day, open_time, close_time, is_closed, created_at, updated_at
`

type UpsertScheduleParams struct {
	ComplexID pgtype.UUID `json:"complex_id"`
	Day       DayOfWeek   `json:"day"`
	OpenTime  pgtype.Time `json:"open_time"`
	CloseTime pgtype.Time `json:"close_time"`
	IsClosed  bool        `json:"is_closed"`
}

func (q *Queries) UpsertSchedule(ctx context.Context, arg UpsertScheduleParams) (ComplexSchedule, error) {
	row := q.db.QueryRow(ctx, upsertSchedule,
		arg.ComplexID,
		arg.Day,
		arg.OpenTime,
		arg.CloseTime,
		arg.IsClosed,
	)
	var i ComplexSchedule
	err := row.Scan(
		&i.ID,
		&i.ComplexID,
		&i.Day,
		&i.OpenTime,
		&i.CloseTime,
		&i.IsClosed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
