// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpCourtVersion = `-- name: BumpCourtVersion :one
UPDATE courts
SET deleted_at = deleted_at
WHERE id = $1
  AND deleted_at IS NULL
  AND ($2::int IS NULL
       OR version = $2::int)
RETURNING id, complex_id, name, sport, court_type, is_active, deleted_at, created_at, updated_at, description, version
`

type BumpCourtVersionParams struct {
	ID              pgtype.UUID `json:"id"`
	ExpectedVersion pgtype.Int4 `json:"expected_version"`
}

// Bumps the court's version without changing any of its own columns, so that
// replacing its price bands moves a counter a client can hold.
//
// The price rows are replaced wholesale (courtstore.Store.ReplacePrices deletes
// them and inserts the new set), so a version on an individual band is gone the
// moment the set is written and cannot be anybody's precondition. The court is
// the thing that persists, so the court's version is the price set's version.
//
// The UPDATE names deleted_at as its assignment precisely because it changes
// nothing: the trigger on this table fires on any UPDATE, which is the whole
// effect wanted here.
func (q *Queries) BumpCourtVersion(ctx context.Context, arg BumpCourtVersionParams) (Court, error) {
	row := q.db.QueryRow(ctx, bumpCourtVersion, arg.ID, arg.ExpectedVersion)
	var i Court
	err := row.Scan(
		&i.ID,
		&i.ComplexID,
		&i.Name,
		&i.Sport,
		&i.CourtType,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.Version,
	)
	return i, err
}

const getCourtByID = `-- name: GetCourtByID :one
SELECT id, complex_id, name, sport, court_type, is_active, deleted_at, created_at, updated_at, description, version FROM active_courts
WHERE id = $1
`

// Reads active_courts: a court whose complex was soft-deleted is not a court
// anyone may book, edit or price, and filtering only on the court's own
// deleted_at missed exactly that case. See the soft-delete cascade in db/migrations/001_init.sql.
func (q *Queries) GetCourtByID(ctx context.Context, id pgtype.UUID) (ActiveCourt, error) {
	row := q.db.QueryRow(ctx, getCourtByID, id)
	var i ActiveCourt
	err := row.Scan(
		&i.ID,
		&i.ComplexID,
		&i.Name,
		&i.Sport,
		&i.CourtType,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.Version,
	)
	return i, err
}

const getCourtsByComplex = `-- name: GetCourtsByComplex :many
SELECT id, complex_id, name, sport, court_type, is_active, deleted_at, created_at, updated_at, description, version FROM active_courts
WHERE complex_id = $1
ORDER BY NULLIF(regexp_replace(name, '\D', '', 'g'), '')::int NULLS LAST, name
`

// Ordered naturally rather than lexically: courts are almost always named
// "Cancha 1", "Cancha 2", ... "Cancha 10", and a plain ORDER BY name sorts
// "Cancha 10" before "Cancha 2". There is no explicit display-order column,
// so the numeric part of the name (if any) is extracted and sorted as an
// integer first, with non-numeric names falling back to plain name order
// after every numbered court.
func (q *Queries) GetCourtsByComplex(ctx context.Context, complexID pgtype.UUID) ([]ActiveCourt, error) {
	rows, err := q.db.Query(ctx, getCourtsByComplex, complexID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActiveCourt
	for rows.Next() {
		var i ActiveCourt
		if err := rows.Scan(
			&i.ID,
			&i.ComplexID,
			&i.Name,
			&i.Sport,
			&i.CourtType,
			&i.IsActive,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCourt = `-- name: InsertCourt :one
INSERT INTO courts (complex_id, name, sport, court_type, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, complex_id, name, sport, court_type, is_active, deleted_at, created_at, updated_at, description, version
`

type InsertCourtParams struct {
	ComplexID   pgtype.UUID `json:"complex_id"`
	Name        string      `json:"name"`
	Sport       SportType   `json:"sport"`
	CourtType   CourtType   `json:"court_type"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) InsertCourt(ctx context.Context, arg InsertCourtParams) (Court, error) {
	row := q.db.QueryRow(ctx, insertCourt,
		arg.ComplexID,
		arg.Name,
		arg.Sport,
		arg.CourtType,
		arg.Description,
	)
	var i Court
	err := row.Scan(
		&i.ID,
		&i.ComplexID,
		&i.Name,
		&i.Sport,
		&i.CourtType,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.Version,
	)
	return i, err
}

const softDeleteCourt = `-- name: SoftDeleteCourt :exec
UPDATE courts
SET deleted_at = NOW(),
    is_active = false
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteCourt(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteCourt, id)
	return err
}

const updateCourt = `-- name: UpdateCourt :one
UPDATE courts
SET name = $1,
    sport = $2,
    court_type = $3,
    is_active = $4,
    description = $5
WHERE id = $6
  AND deleted_at IS NULL
  AND ($7::int IS NULL
       OR version = $7::int)
RETURNING id, complex_id, name, sport, court_type, is_active, deleted_at, created_at, updated_at, description, version
`

type UpdateCourtParams struct {
	Name            string      `json:"name"`
	Sport           SportType   `json:"sport"`
	CourtType       CourtType   `json:"court_type"`
	IsActive        bool        `json:"is_active"`
	Description     pgtype.Text `json:"description"`
	ID              pgtype.UUID `json:"id"`
	ExpectedVersion pgtype.Int4 `json:"expected_version"`
}

// expected_version is the caller's optimistic-concurrency precondition and is
// optional (API-08): NULL is the last-write-wins this endpoint had before
// versions existed. Zero rows means either the court is gone or somebody else
// wrote it first; courtstore.Store.Update tells those apart by re-reading.
func (q *Queries) UpdateCourt(ctx context.Context, arg UpdateCourtParams) (Court, error) {
	row := q.db.QueryRow(ctx, updateCourt,
		arg.Name,
		arg.Sport,
		arg.CourtType,
		arg.IsActive,
		arg.Description,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i Court
	err := row.Scan(
		&i.ID,
		&i.ComplexID,
		&i.Name,
		&i.Sport,
		&i.CourtType,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.Version,
	)
	return i, err
}
