// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: court_prices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCourtPrice = `-- name: DeleteCourtPrice :exec
DELETE FROM court_prices
WHERE id = $1
`

func (q *Queries) DeleteCourtPrice(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCourtPrice, id)
	return err
}

const getCourtPrices = `-- name: GetCourtPrices :many
SELECT id, court_id, price, day_type, time_from, time_to, created_at, updated_at, span_min FROM court_prices
WHERE court_id = $1
ORDER BY day_type, time_from
`

func (q *Queries) GetCourtPrices(ctx context.Context, courtID pgtype.UUID) ([]CourtPrice, error) {
	rows, err := q.db.Query(ctx, getCourtPrices, courtID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CourtPrice
	for rows.Next() {
		var i CourtPrice
		if err := rows.Scan(
			&i.ID,
			&i.CourtID,
			&i.Price,
			&i.DayType,
			&i.TimeFrom,
			&i.TimeTo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SpanMin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCourtPrice = `-- name: InsertCourtPrice :one
INSERT INTO court_prices (court_id, price, day_type, time_from, time_to)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, court_id, price, day_type, time_from, time_to, created_at, updated_at, span_min
`

type InsertCourtPriceParams struct {
	CourtID  pgtype.UUID `json:"court_id"`
	Price    int32       `json:"price"`
	DayType  DayOfWeek   `json:"day_type"`
	TimeFrom pgtype.Time `json:"time_from"`
	TimeTo   pgtype.Time `json:"time_to"`
}

func (q *Queries) InsertCourtPrice(ctx context.Context, arg InsertCourtPriceParams) (CourtPrice, error) {
	row := q.db.QueryRow(ctx, insertCourtPrice,
		arg.CourtID,
		arg.Price,
		arg.DayType,
		arg.TimeFrom,
		arg.TimeTo,
	)
	var i CourtPrice
	err := row.Scan(
		&i.ID,
		&i.CourtID,
		&i.Price,
		&i.DayType,
		&i.TimeFrom,
		&i.TimeTo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SpanMin,
	)
	return i, err
}

const updateCourtPrice = `-- name: UpdateCourtPrice :one
UPDATE court_prices
SET price = $1,
    day_type = $2,
    time_from = $3,
    time_to = $4
WHERE id = $5
RETURNING id, court_id, price, day_type, time_from, time_to, created_at, updated_at, span_min
`

type UpdateCourtPriceParams struct {
	Price    int32       `json:"price"`
	DayType  DayOfWeek   `json:"day_type"`
	TimeFrom pgtype.Time `json:"time_from"`
	TimeTo   pgtype.Time `json:"time_to"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateCourtPrice(ctx context.Context, arg UpdateCourtPriceParams) (CourtPrice, error) {
	row := q.db.QueryRow(ctx, updateCourtPrice,
		arg.Price,
		arg.DayType,
		arg.TimeFrom,
		arg.TimeTo,
		arg.ID,
	)
	var i CourtPrice
	err := row.Scan(
		&i.ID,
		&i.CourtID,
		&i.Price,
		&i.DayType,
		&i.TimeFrom,
		&i.TimeTo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SpanMin,
	)
	return i, err
}
