// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type BookingStatus string

const (
	BookingStatusPending   BookingStatus = "pending"
	BookingStatusConfirmed BookingStatus = "confirmed"
	BookingStatusCancelled BookingStatus = "cancelled"
	BookingStatusCompleted BookingStatus = "completed"
	BookingStatusNoShow    BookingStatus = "no_show"
)

func (e *BookingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BookingStatus(s)
	case string:
		*e = BookingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BookingStatus: %T", src)
	}
	return nil
}

type NullBookingStatus struct {
	BookingStatus BookingStatus `json:"booking_status"`
	Valid         bool          `json:"valid"` // Valid is true if BookingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBookingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BookingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BookingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBookingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BookingStatus), nil
}

type CourtType string

const (
	CourtTypeIndoor      CourtType = "indoor"
	CourtTypeOutdoor     CourtType = "outdoor"
	CourtTypeSemiCovered CourtType = "semi_covered"
)

func (e *CourtType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CourtType(s)
	case string:
		*e = CourtType(s)
	default:
		return fmt.Errorf("unsupported scan type for CourtType: %T", src)
	}
	return nil
}

type NullCourtType struct {
	CourtType CourtType `json:"court_type"`
	Valid     bool      `json:"valid"` // Valid is true if CourtType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCourtType) Scan(value interface{}) error {
	if value == nil {
		ns.CourtType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CourtType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCourtType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CourtType), nil
}

type DayOfWeek string

const (
	DayOfWeekMonday    DayOfWeek = "monday"
	DayOfWeekTuesday   DayOfWeek = "tuesday"
	DayOfWeekWednesday DayOfWeek = "wednesday"
	DayOfWeekThursday  DayOfWeek = "thursday"
	DayOfWeekFriday    DayOfWeek = "friday"
	DayOfWeekSaturday  DayOfWeek = "saturday"
	DayOfWeekSunday    DayOfWeek = "sunday"
)

func (e *DayOfWeek) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DayOfWeek(s)
	case string:
		*e = DayOfWeek(s)
	default:
		return fmt.Errorf("unsupported scan type for DayOfWeek: %T", src)
	}
	return nil
}

type NullDayOfWeek struct {
	DayOfWeek DayOfWeek `json:"day_of_week"`
	Valid     bool      `json:"valid"` // Valid is true if DayOfWeek is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDayOfWeek) Scan(value interface{}) error {
	if value == nil {
		ns.DayOfWeek, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DayOfWeek.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDayOfWeek) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DayOfWeek), nil
}

type PaymentMethod string

const (
	PaymentMethodMercadopago PaymentMethod = "mercadopago"
	PaymentMethodCash        PaymentMethod = "cash"
	PaymentMethodTransfer    PaymentMethod = "transfer"
	PaymentMethodDebitCard   PaymentMethod = "debit_card"
	PaymentMethodCreditCard  PaymentMethod = "credit_card"
	PaymentMethodQrWallet    PaymentMethod = "qr_wallet"
)

func (e *PaymentMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentMethod(s)
	case string:
		*e = PaymentMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentMethod: %T", src)
	}
	return nil
}

type NullPaymentMethod struct {
	PaymentMethod PaymentMethod `json:"payment_method"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentMethod) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentMethod), nil
}

type PaymentStatus string

const (
	PaymentStatusUnpaid        PaymentStatus = "unpaid"
	PaymentStatusDepositPaid   PaymentStatus = "deposit_paid"
	PaymentStatusFullyPaid     PaymentStatus = "fully_paid"
	PaymentStatusRefunded      PaymentStatus = "refunded"
	PaymentStatusRefundPending PaymentStatus = "refund_pending"
	PaymentStatusPartialRefund PaymentStatus = "partial_refund"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus `json:"payment_status"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type SportType string

const (
	SportTypePadel      SportType = "padel"
	SportTypeTennis     SportType = "tennis"
	SportTypeSoccer     SportType = "soccer"
	SportTypeBasketball SportType = "basketball"
	SportTypeVolleyball SportType = "volleyball"
	SportTypeHockey     SportType = "hockey"
	SportTypePickleball SportType = "pickleball"
)

func (e *SportType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SportType(s)
	case string:
		*e = SportType(s)
	default:
		return fmt.Errorf("unsupported scan type for SportType: %T", src)
	}
	return nil
}

type NullSportType struct {
	SportType SportType `json:"sport_type"`
	Valid     bool      `json:"valid"` // Valid is true if SportType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSportType) Scan(value interface{}) error {
	if value == nil {
		ns.SportType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SportType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSportType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SportType), nil
}

type UserRole string

const (
	UserRoleOwner      UserRole = "owner"
	UserRoleClient     UserRole = "client"
	UserRoleSuperadmin UserRole = "superadmin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

// Complexes that are not soft-deleted. Read this, not the table, unless the caller needs deleted rows (admin, audit, slug reservation).
type ActiveComplex struct {
	ID                pgtype.UUID        `json:"id"`
	OwnerID           pgtype.UUID        `json:"owner_id"`
	Name              string             `json:"name"`
	Slug              string             `json:"slug"`
	Address           string             `json:"address"`
	City              string             `json:"city"`
	Province          string             `json:"province"`
	CountryCode       string             `json:"country_code"`
	Currency          string             `json:"currency"`
	Phone             string             `json:"phone"`
	Email             pgtype.Text        `json:"email"`
	LogoUrl           pgtype.Text        `json:"logo_url"`
	CoverUrl          pgtype.Text        `json:"cover_url"`
	DepositPercentage int32              `json:"deposit_percentage"`
	CancellationHours int32              `json:"cancellation_hours"`
	Latitude          pgtype.Float8      `json:"latitude"`
	Longitude         pgtype.Float8      `json:"longitude"`
	IsActive          bool               `json:"is_active"`
	MpAccessToken     pgtype.Text        `json:"mp_access_token"`
	MpRefreshToken    pgtype.Text        `json:"mp_refresh_token"`
	MpUserID          pgtype.Text        `json:"mp_user_id"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Amenities         []string           `json:"amenities"`
	MpTokenExpiresAt  pgtype.Timestamptz `json:"mp_token_expires_at"`
	Version           int32              `json:"version"`
}

// Courts that are not soft-deleted and whose complex is not soft-deleted either. Read this, not the table, unless the caller needs deleted rows (admin, audit, the court name on a historical booking).
type ActiveCourt struct {
	ID          pgtype.UUID        `json:"id"`
	ComplexID   pgtype.UUID        `json:"complex_id"`
	Name        string             `json:"name"`
	Sport       SportType          `json:"sport"`
	CourtType   CourtType          `json:"court_type"`
	IsActive    bool               `json:"is_active"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Description pgtype.Text        `json:"description"`
	Version     int32              `json:"version"`
}

type AuditLog struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	ComplexID  pgtype.UUID        `json:"complex_id"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	OldValue   []byte             `json:"old_value"`
	NewValue   []byte             `json:"new_value"`
	IpAddress  *netip.Addr        `json:"ip_address"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type BlockedSlot struct {
	ID        pgtype.UUID                      `json:"id"`
	CourtID   pgtype.UUID                      `json:"court_id"`
	Date      pgtype.Date                      `json:"date"`
	StartTime pgtype.Time                      `json:"start_time"`
	EndTime   pgtype.Time                      `json:"end_time"`
	Reason    pgtype.Text                      `json:"reason"`
	CreatedBy pgtype.UUID                      `json:"created_by"`
	CreatedAt pgtype.Timestamptz               `json:"created_at"`
	UpdatedAt pgtype.Timestamptz               `json:"updated_at"`
	Span      pgtype.Range[pgtype.Timestamptz] `json:"span"`
	ComplexID pgtype.UUID                      `json:"complex_id"`
}

type Booking struct {
	ID               pgtype.UUID                      `json:"id"`
	ComplexID        pgtype.UUID                      `json:"complex_id"`
	CourtID          pgtype.UUID                      `json:"court_id"`
	ClientID         pgtype.UUID                      `json:"client_id"`
	Date             pgtype.Date                      `json:"date"`
	StartTime        pgtype.Time                      `json:"start_time"`
	DurationMinutes  int32                            `json:"duration_minutes"`
	Price            int32                            `json:"price"`
	DepositAmount    int32                            `json:"deposit_amount"`
	Status           BookingStatus                    `json:"status"`
	ReminderSent2h   bool                             `json:"reminder_sent_2h"`
	Notes            pgtype.Text                      `json:"notes"`
	CreatedBy        pgtype.UUID                      `json:"created_by"`
	CreatedAt        pgtype.Timestamptz               `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz               `json:"updated_at"`
	RefundIntentAt   pgtype.Timestamptz               `json:"refund_intent_at"`
	Span             pgtype.Range[pgtype.Timestamptz] `json:"span"`
	CollectionStatus string                           `json:"collection_status"`
	RefundStatus     string                           `json:"refund_status"`
}

type BookingLinkToken struct {
	ID        pgtype.UUID        `json:"id"`
	BookingID pgtype.UUID        `json:"booking_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ComplexID pgtype.UUID        `json:"complex_id"`
}

type CashMovement struct {
	ID              pgtype.UUID        `json:"id"`
	ComplexID       pgtype.UUID        `json:"complex_id"`
	SessionID       pgtype.UUID        `json:"session_id"`
	Kind            string             `json:"kind"`
	Category        string             `json:"category"`
	Method          PaymentMethod      `json:"method"`
	Amount          int32              `json:"amount"`
	Note            pgtype.Text        `json:"note"`
	VoidsMovementID pgtype.UUID        `json:"voids_movement_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
}

type CashSession struct {
	ID           pgtype.UUID        `json:"id"`
	ComplexID    pgtype.UUID        `json:"complex_id"`
	OpenedAt     pgtype.Timestamptz `json:"opened_at"`
	OpenedBy     pgtype.UUID        `json:"opened_by"`
	OpeningCash  int64              `json:"opening_cash"`
	ClosedAt     pgtype.Timestamptz `json:"closed_at"`
	ClosedBy     pgtype.UUID        `json:"closed_by"`
	CountedCash  pgtype.Int8        `json:"counted_cash"`
	ExpectedCash pgtype.Int8        `json:"expected_cash"`
	Difference   pgtype.Int8        `json:"difference"`
	OpeningNote  pgtype.Text        `json:"opening_note"`
	ClosingNote  pgtype.Text        `json:"closing_note"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Client struct {
	ID            pgtype.UUID        `json:"id"`
	ComplexID     pgtype.UUID        `json:"complex_id"`
	FirstName     string             `json:"first_name"`
	LastName      string             `json:"last_name"`
	Phone         string             `json:"phone"`
	Email         pgtype.Text        `json:"email"`
	Notes         pgtype.Text        `json:"notes"`
	IsBlocked     bool               `json:"is_blocked"`
	TotalBookings int32              `json:"total_bookings"`
	NoShows       int32              `json:"no_shows"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Complex struct {
	ID                pgtype.UUID        `json:"id"`
	OwnerID           pgtype.UUID        `json:"owner_id"`
	Name              string             `json:"name"`
	Slug              string             `json:"slug"`
	Address           string             `json:"address"`
	City              string             `json:"city"`
	Province          string             `json:"province"`
	CountryCode       string             `json:"country_code"`
	Currency          string             `json:"currency"`
	Phone             string             `json:"phone"`
	Email             pgtype.Text        `json:"email"`
	LogoUrl           pgtype.Text        `json:"logo_url"`
	CoverUrl          pgtype.Text        `json:"cover_url"`
	DepositPercentage int32              `json:"deposit_percentage"`
	CancellationHours int32              `json:"cancellation_hours"`
	Latitude          pgtype.Float8      `json:"latitude"`
	Longitude         pgtype.Float8      `json:"longitude"`
	IsActive          bool               `json:"is_active"`
	MpAccessToken     pgtype.Text        `json:"mp_access_token"`
	MpRefreshToken    pgtype.Text        `json:"mp_refresh_token"`
	MpUserID          pgtype.Text        `json:"mp_user_id"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Amenities         []string           `json:"amenities"`
	MpTokenExpiresAt  pgtype.Timestamptz `json:"mp_token_expires_at"`
	Version           int32              `json:"version"`
}

type ComplexSchedule struct {
	ID        pgtype.UUID        `json:"id"`
	ComplexID pgtype.UUID        `json:"complex_id"`
	Day       DayOfWeek          `json:"day"`
	OpenTime  pgtype.Time        `json:"open_time"`
	CloseTime pgtype.Time        `json:"close_time"`
	IsClosed  bool               `json:"is_closed"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Court struct {
	ID          pgtype.UUID        `json:"id"`
	ComplexID   pgtype.UUID        `json:"complex_id"`
	Name        string             `json:"name"`
	Sport       SportType          `json:"sport"`
	CourtType   CourtType          `json:"court_type"`
	IsActive    bool               `json:"is_active"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Description pgtype.Text        `json:"description"`
	Version     int32              `json:"version"`
}

type CourtPrice struct {
	ID      pgtype.UUID `json:"id"`
	CourtID pgtype.UUID `json:"court_id"`
	// Hourly rate in centavos (price per 60 minutes), in effect for [time_from, time_to) on day_type. A booking of any permitted duration is priced by walking it in 30-minute blocks against this rate (internal/pricing.BookingPrice).
	Price     int32                     `json:"price"`
	DayType   DayOfWeek                 `json:"day_type"`
	TimeFrom  pgtype.Time               `json:"time_from"`
	TimeTo    pgtype.Time               `json:"time_to"`
	CreatedAt pgtype.Timestamptz        `json:"created_at"`
	UpdatedAt pgtype.Timestamptz        `json:"updated_at"`
	SpanMin   pgtype.Range[pgtype.Int4] `json:"span_min"`
	Version   int32                     `json:"version"`
	ComplexID pgtype.UUID               `json:"complex_id"`
}

type EmailChangeRequest struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	NewEmail  string             `json:"new_email"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type EmailVerificationToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type FailedRefund struct {
	ID           pgtype.UUID        `json:"id"`
	PaymentID    pgtype.UUID        `json:"payment_id"`
	BookingID    pgtype.UUID        `json:"booking_id"`
	ComplexID    pgtype.UUID        `json:"complex_id"`
	Amount       int32              `json:"amount"`
	MpPaymentID  pgtype.Text        `json:"mp_payment_id"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	RetryCount   int32              `json:"retry_count"`
	MaxRetries   int32              `json:"max_retries"`
	NextRetryAt  pgtype.Timestamptz `json:"next_retry_at"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ResolvedAt   pgtype.Timestamptz `json:"resolved_at"`
}

// The durable work queue. Claimed with SELECT ... FOR UPDATE SKIP LOCKED; see internal/jobs.
type Job struct {
	ID      pgtype.UUID        `json:"id"`
	Type    string             `json:"type"`
	Payload []byte             `json:"payload"`
	Status  string             `json:"status"`
	RunAt   pgtype.Timestamptz `json:"run_at"`
	// Claims, not failures: incremented by the claim itself, so a handler that kills the process still spends one.
	Attempts    int32              `json:"attempts"`
	MaxAttempts int32              `json:"max_attempts"`
	LastError   pgtype.Text        `json:"last_error"`
	LockedAt    pgtype.Timestamptz `json:"locked_at"`
	LockedBy    pgtype.Text        `json:"locked_by"`
	// sha256 of the job type and what identifies the work (recipient, booking, event). A second enqueue under an existing key does nothing.
	DedupKey  pgtype.Text        `json:"dedup_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type JobLock struct {
	Key        string             `json:"key"`
	Holder     pgtype.UUID        `json:"holder"`
	AcquiredAt pgtype.Timestamptz `json:"acquired_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

type PasswordResetToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Payment struct {
	ID             pgtype.UUID        `json:"id"`
	BookingID      pgtype.UUID        `json:"booking_id"`
	ComplexID      pgtype.UUID        `json:"complex_id"`
	Amount         int32              `json:"amount"`
	ServiceFee     int32              `json:"service_fee"`
	Method         PaymentMethod      `json:"method"`
	Status         PaymentStatus      `json:"status"`
	MpPaymentID    pgtype.Text        `json:"mp_payment_id"`
	MpPreferenceID pgtype.Text        `json:"mp_preference_id"`
	RefundAmount   int32              `json:"refund_amount"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	StatusDetail   pgtype.Text        `json:"status_detail"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SlotLock struct {
	ID        pgtype.UUID        `json:"id"`
	CourtID   pgtype.UUID        `json:"court_id"`
	Date      pgtype.Date        `json:"date"`
	StartTime pgtype.Time        `json:"start_time"`
	EndTime   pgtype.Time        `json:"end_time"`
	BookingID pgtype.UUID        `json:"booking_id"`
	LockedBy  string             `json:"locked_by"`
	LockedAt  pgtype.Timestamptz `json:"locked_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	ComplexID pgtype.UUID        `json:"complex_id"`
}

type User struct {
	ID                  pgtype.UUID        `json:"id"`
	Email               string             `json:"email"`
	PasswordHash        []byte             `json:"password_hash"`
	FirstName           string             `json:"first_name"`
	LastName            string             `json:"last_name"`
	Phone               string             `json:"phone"`
	Role                UserRole           `json:"role"`
	IsActive            bool               `json:"is_active"`
	FailedLoginAttempts int32              `json:"failed_login_attempts"`
	LockedUntil         pgtype.Timestamptz `json:"locked_until"`
	LastFailedLogin     pgtype.Timestamptz `json:"last_failed_login"`
	EmailVerified       bool               `json:"email_verified"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type UserIdentity struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Provider  string             `json:"provider"`
	Subject   string             `json:"subject"`
	Email     pgtype.Text        `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type WebhookEvent struct {
	ID          pgtype.UUID        `json:"id"`
	Provider    string             `json:"provider"`
	ExternalID  string             `json:"external_id"`
	EventType   string             `json:"event_type"`
	Payload     []byte             `json:"payload"`
	Status      string             `json:"status"`
	RetryCount  int32              `json:"retry_count"`
	MaxRetries  int32              `json:"max_retries"`
	NextRetryAt pgtype.Timestamptz `json:"next_retry_at"`
	LastError   pgtype.Text        `json:"last_error"`
	ReceivedAt  pgtype.Timestamptz `json:"received_at"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
