// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPaymentByBookingID = `-- name: GetPaymentByBookingID :one
SELECT id, booking_id, complex_id, amount, service_fee, method, status, mp_payment_id, mp_preference_id, refund_amount, created_at, updated_at, status_detail FROM payments
WHERE booking_id = $1
ORDER BY (mp_payment_id IS NOT NULL) DESC, created_at DESC
LIMIT 1
`

// A booking can legitimately have more than one payment row (the checkout row plus a
// cash row inserted by ConfirmPayment), and idx_payments_booking is not unique, so
// without an explicit order the driver returns an arbitrary row. Prefer the MercadoPago
// row: it is the one carrying mp_payment_id, which the refund path needs.
func (q *Queries) GetPaymentByBookingID(ctx context.Context, bookingID pgtype.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByBookingID, bookingID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.ComplexID,
		&i.Amount,
		&i.ServiceFee,
		&i.Method,
		&i.Status,
		&i.MpPaymentID,
		&i.MpPreferenceID,
		&i.RefundAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StatusDetail,
	)
	return i, err
}

const getPaymentByIDForUpdate = `-- name: GetPaymentByIDForUpdate :one
SELECT id, booking_id, complex_id, amount, service_fee, method, status, mp_payment_id, mp_preference_id, refund_amount, created_at, updated_at, status_detail FROM payments
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetPaymentByIDForUpdate(ctx context.Context, id pgtype.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByIDForUpdate, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.ComplexID,
		&i.Amount,
		&i.ServiceFee,
		&i.Method,
		&i.Status,
		&i.MpPaymentID,
		&i.MpPreferenceID,
		&i.RefundAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StatusDetail,
	)
	return i, err
}

const getPaymentByMPID = `-- name: GetPaymentByMPID :one
SELECT id, booking_id, complex_id, amount, service_fee, method, status, mp_payment_id, mp_preference_id, refund_amount, created_at, updated_at, status_detail FROM payments
WHERE mp_payment_id = $1
`

func (q *Queries) GetPaymentByMPID(ctx context.Context, mpPaymentID pgtype.Text) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByMPID, mpPaymentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.ComplexID,
		&i.Amount,
		&i.ServiceFee,
		&i.Method,
		&i.Status,
		&i.MpPaymentID,
		&i.MpPreferenceID,
		&i.RefundAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StatusDetail,
	)
	return i, err
}

const insertPayment = `-- name: InsertPayment :one
INSERT INTO payments (booking_id, complex_id, amount, method, status, service_fee, mp_payment_id, mp_preference_id, status_detail)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, booking_id, complex_id, amount, service_fee, method, status, mp_payment_id, mp_preference_id, refund_amount, created_at, updated_at, status_detail
`

type InsertPaymentParams struct {
	BookingID      pgtype.UUID   `json:"booking_id"`
	ComplexID      pgtype.UUID   `json:"complex_id"`
	Amount         int32         `json:"amount"`
	Method         PaymentMethod `json:"method"`
	Status         PaymentStatus `json:"status"`
	ServiceFee     int32         `json:"service_fee"`
	MpPaymentID    pgtype.Text   `json:"mp_payment_id"`
	MpPreferenceID pgtype.Text   `json:"mp_preference_id"`
	StatusDetail   pgtype.Text   `json:"status_detail"`
}

func (q *Queries) InsertPayment(ctx context.Context, arg InsertPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, insertPayment,
		arg.BookingID,
		arg.ComplexID,
		arg.Amount,
		arg.Method,
		arg.Status,
		arg.ServiceFee,
		arg.MpPaymentID,
		arg.MpPreferenceID,
		arg.StatusDetail,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.ComplexID,
		&i.Amount,
		&i.ServiceFee,
		&i.Method,
		&i.Status,
		&i.MpPaymentID,
		&i.MpPreferenceID,
		&i.RefundAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StatusDetail,
	)
	return i, err
}

const listPaymentsByBookingID = `-- name: ListPaymentsByBookingID :many
SELECT id, booking_id, complex_id, amount, service_fee, method, status, mp_payment_id, mp_preference_id, refund_amount, created_at, updated_at, status_detail FROM payments
WHERE booking_id = $1
ORDER BY created_at ASC
`

// Every payment row of a booking, oldest first (the deposit before the balance),
// for callers that need the whole ledger rather than one row — the refund path
// sums money and the booking detail shows each payment; GetPaymentByBookingID's
// single MercadoPago-preferred row is for callers that need that one row.
func (q *Queries) ListPaymentsByBookingID(ctx context.Context, bookingID pgtype.UUID) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByBookingID, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.ComplexID,
			&i.Amount,
			&i.ServiceFee,
			&i.Method,
			&i.Status,
			&i.MpPaymentID,
			&i.MpPreferenceID,
			&i.RefundAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StatusDetail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePayment = `-- name: UpdatePayment :one
UPDATE payments
SET status = $1,
    mp_payment_id = $2,
    mp_preference_id = $3,
    refund_amount = $4,
    status_detail = $5
WHERE id = $6
RETURNING id, booking_id, complex_id, amount, service_fee, method, status, mp_payment_id, mp_preference_id, refund_amount, created_at, updated_at, status_detail
`

type UpdatePaymentParams struct {
	Status         PaymentStatus `json:"status"`
	MpPaymentID    pgtype.Text   `json:"mp_payment_id"`
	MpPreferenceID pgtype.Text   `json:"mp_preference_id"`
	RefundAmount   int32         `json:"refund_amount"`
	StatusDetail   pgtype.Text   `json:"status_detail"`
	ID             pgtype.UUID   `json:"id"`
}

func (q *Queries) UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePayment,
		arg.Status,
		arg.MpPaymentID,
		arg.MpPreferenceID,
		arg.RefundAmount,
		arg.StatusDetail,
		arg.ID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.ComplexID,
		&i.Amount,
		&i.ServiceFee,
		&i.Method,
		&i.Status,
		&i.MpPaymentID,
		&i.MpPreferenceID,
		&i.RefundAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StatusDetail,
	)
	return i, err
}
