// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProductByID = `-- name: GetProductByID :one
SELECT id, complex_id, name, category, price, tracks_stock, stock_on_hand, low_stock_threshold, active, created_at, updated_at, version FROM products
WHERE id = $1 AND complex_id = $2
`

type GetProductByIDParams struct {
	ID        pgtype.UUID `json:"id"`
	ComplexID pgtype.UUID `json:"complex_id"`
}

func (q *Queries) GetProductByID(ctx context.Context, arg GetProductByIDParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, arg.ID, arg.ComplexID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ComplexID,
		&i.Name,
		&i.Category,
		&i.Price,
		&i.TracksStock,
		&i.StockOnHand,
		&i.LowStockThreshold,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getProductByIDForUpdate = `-- name: GetProductByIDForUpdate :one
SELECT id, complex_id, name, category, price, tracks_stock, stock_on_hand, low_stock_threshold, active, created_at, updated_at, version FROM products
WHERE id = $1 AND complex_id = $2
FOR UPDATE
`

type GetProductByIDForUpdateParams struct {
	ID        pgtype.UUID `json:"id"`
	ComplexID pgtype.UUID `json:"complex_id"`
}

// Every write against a product (an update, a restock, an adjustment) locks
// the row first, in the same transaction as the write, so stock_on_hand can
// never be read-modify-written by two requests at once.
func (q *Queries) GetProductByIDForUpdate(ctx context.Context, arg GetProductByIDForUpdateParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByIDForUpdate, arg.ID, arg.ComplexID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ComplexID,
		&i.Name,
		&i.Category,
		&i.Price,
		&i.TracksStock,
		&i.StockOnHand,
		&i.LowStockThreshold,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const insertProduct = `-- name: InsertProduct :one
INSERT INTO products (complex_id, name, category, price, tracks_stock, low_stock_threshold)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, complex_id, name, category, price, tracks_stock, stock_on_hand, low_stock_threshold, active, created_at, updated_at, version
`

type InsertProductParams struct {
	ComplexID         pgtype.UUID `json:"complex_id"`
	Name              string      `json:"name"`
	Category          pgtype.Text `json:"category"`
	Price             int32       `json:"price"`
	TracksStock       bool        `json:"tracks_stock"`
	LowStockThreshold pgtype.Int4 `json:"low_stock_threshold"`
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, insertProduct,
		arg.ComplexID,
		arg.Name,
		arg.Category,
		arg.Price,
		arg.TracksStock,
		arg.LowStockThreshold,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ComplexID,
		&i.Name,
		&i.Category,
		&i.Price,
		&i.TracksStock,
		&i.StockOnHand,
		&i.LowStockThreshold,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const insertStockMovement = `-- name: InsertStockMovement :one
INSERT INTO stock_movements (complex_id, product_id, kind, quantity, reason, note, cash_movement_id, sale_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, complex_id, product_id, kind, quantity, reason, note, cash_movement_id, sale_id, created_at, created_by
`

type InsertStockMovementParams struct {
	ComplexID      pgtype.UUID `json:"complex_id"`
	ProductID      pgtype.UUID `json:"product_id"`
	Kind           string      `json:"kind"`
	Quantity       int32       `json:"quantity"`
	Reason         pgtype.Text `json:"reason"`
	Note           pgtype.Text `json:"note"`
	CashMovementID pgtype.UUID `json:"cash_movement_id"`
	SaleID         pgtype.UUID `json:"sale_id"`
	CreatedBy      pgtype.UUID `json:"created_by"`
}

func (q *Queries) InsertStockMovement(ctx context.Context, arg InsertStockMovementParams) (StockMovement, error) {
	row := q.db.QueryRow(ctx, insertStockMovement,
		arg.ComplexID,
		arg.ProductID,
		arg.Kind,
		arg.Quantity,
		arg.Reason,
		arg.Note,
		arg.CashMovementID,
		arg.SaleID,
		arg.CreatedBy,
	)
	var i StockMovement
	err := row.Scan(
		&i.ID,
		&i.ComplexID,
		&i.ProductID,
		&i.Kind,
		&i.Quantity,
		&i.Reason,
		&i.Note,
		&i.CashMovementID,
		&i.SaleID,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listProductsByComplex = `-- name: ListProductsByComplex :many
SELECT id, complex_id, name, category, price, tracks_stock, stock_on_hand, low_stock_threshold, active, created_at, updated_at, version FROM products
WHERE complex_id = $1
  AND (NOT $2::bool OR active = $3::bool)
ORDER BY name ASC
`

type ListProductsByComplexParams struct {
	ComplexID       pgtype.UUID `json:"complex_id"`
	HasActiveFilter bool        `json:"has_active_filter"`
	ActiveFilter    bool        `json:"active_filter"`
}

// Not paginated — a shop's catalog is bounded the same way a complex's court
// list is (internal/courts/store's GetByComplex). has_active_filter is false
// when the caller asked for every product regardless of active state; the OR's
// left side short-circuits instead of comparing against a meaningless
// active_filter value.
func (q *Queries) ListProductsByComplex(ctx context.Context, arg ListProductsByComplexParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByComplex, arg.ComplexID, arg.HasActiveFilter, arg.ActiveFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ComplexID,
			&i.Name,
			&i.Category,
			&i.Price,
			&i.TracksStock,
			&i.StockOnHand,
			&i.LowStockThreshold,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockMovementsByProduct = `-- name: ListStockMovementsByProduct :many
SELECT id, complex_id, product_id, kind, quantity, reason, note, cash_movement_id, sale_id, created_at, created_by FROM stock_movements
WHERE product_id = $1 AND complex_id = $2
  AND (NOT $3::bool
       OR (created_at, id) < ($4::timestamptz, $5::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $6::int
`

type ListStockMovementsByProductParams struct {
	ProductID       pgtype.UUID        `json:"product_id"`
	ComplexID       pgtype.UUID        `json:"complex_id"`
	HasCursor       bool               `json:"has_cursor"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

// Keyset pagination, same shape as cash_sessions' own ListCashSessionsByComplex.
func (q *Queries) ListStockMovementsByProduct(ctx context.Context, arg ListStockMovementsByProductParams) ([]StockMovement, error) {
	rows, err := q.db.Query(ctx, listStockMovementsByProduct,
		arg.ProductID,
		arg.ComplexID,
		arg.HasCursor,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockMovement
	for rows.Next() {
		var i StockMovement
		if err := rows.Scan(
			&i.ID,
			&i.ComplexID,
			&i.ProductID,
			&i.Kind,
			&i.Quantity,
			&i.Reason,
			&i.Note,
			&i.CashMovementID,
			&i.SaleID,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = $1,
    category = $2,
    price = $3,
    low_stock_threshold = $4,
    active = $5,
    tracks_stock = $6
WHERE id = $7
  AND complex_id = $8
  AND ($9::int IS NULL
       OR version = $9::int)
RETURNING id, complex_id, name, category, price, tracks_stock, stock_on_hand, low_stock_threshold, active, created_at, updated_at, version
`

type UpdateProductParams struct {
	Name              string      `json:"name"`
	Category          pgtype.Text `json:"category"`
	Price             int32       `json:"price"`
	LowStockThreshold pgtype.Int4 `json:"low_stock_threshold"`
	Active            bool        `json:"active"`
	TracksStock       bool        `json:"tracks_stock"`
	ID                pgtype.UUID `json:"id"`
	ComplexID         pgtype.UUID `json:"complex_id"`
	ExpectedVersion   pgtype.Int4 `json:"expected_version"`
}

// expected_version is the caller's optimistic-concurrency precondition and is
// optional (API-08): NULL is last-write-wins. Zero rows means either the
// product is gone or somebody else wrote it first; products/store.Store.Update
// tells those apart the same way courtstore.Store.Update does (a prior read
// already proved existence, so a zero-row result here can only be the second
// case).
func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.Name,
		arg.Category,
		arg.Price,
		arg.LowStockThreshold,
		arg.Active,
		arg.TracksStock,
		arg.ID,
		arg.ComplexID,
		arg.ExpectedVersion,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ComplexID,
		&i.Name,
		&i.Category,
		&i.Price,
		&i.TracksStock,
		&i.StockOnHand,
		&i.LowStockThreshold,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const updateProductStock = `-- name: UpdateProductStock :one
UPDATE products
SET stock_on_hand = stock_on_hand + $3::int
WHERE id = $1 AND complex_id = $2
RETURNING id, complex_id, name, category, price, tracks_stock, stock_on_hand, low_stock_threshold, active, created_at, updated_at, version
`

type UpdateProductStockParams struct {
	ID        pgtype.UUID `json:"id"`
	ComplexID pgtype.UUID `json:"complex_id"`
	Delta     int32       `json:"delta"`
}

// Applies a stock movement's signed quantity to the product's own running
// total, in the same transaction as the movement insert
// (internal/products/store.Store.Restock / .Adjust), under the FOR UPDATE lock
// GetProductByIDForUpdate already took. stock_on_hand may go negative — see
// that column's own comment in db/migrations/004_pos_catalog_stock.sql.
func (q *Queries) UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductStock, arg.ID, arg.ComplexID, arg.Delta)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ComplexID,
		&i.Name,
		&i.Category,
		&i.Price,
		&i.TracksStock,
		&i.StockOnHand,
		&i.LowStockThreshold,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
