// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Bumps the court's version without changing any of its own columns, so that
	// replacing its price bands moves a counter a client can hold.
	//
	// The price rows are replaced wholesale (courtstore.Store.ReplacePrices deletes
	// them and inserts the new set), so a version on an individual band is gone the
	// moment the set is written and cannot be anybody's precondition. The court is
	// the thing that persists, so the court's version is the price set's version.
	//
	// The UPDATE names deleted_at as its assignment precisely because it changes
	// nothing: the trigger on this table fires on any UPDATE, which is the whole
	// effect wanted here.
	BumpCourtVersion(ctx context.Context, arg BumpCourtVersionParams) (Court, error)
	// closing_note is its own column: it never touches opening_note, so a
	// closing note can never erase what Open recorded.
	//
	// closed_at is a PARAMETER, not NOW(): the service reads booking payments
	// over a window ending at one instant it picked itself, and that same
	// instant has to be what lands in closed_at, or a payment landing between
	// the service's read and this UPDATE's own NOW() would be missing from the
	// stored expected_cash yet appear in a summary later rebuilt over
	// [opened_at, closed_at) — see Service.Close's own comment.
	CloseCashSession(ctx context.Context, arg CloseCashSessionParams) (CashSession, error)
	DeleteAllRefreshTokensByUser(ctx context.Context, userID pgtype.UUID) error
	DeleteBlockedSlot(ctx context.Context, id pgtype.UUID) error
	DeleteCourtPrice(ctx context.Context, id pgtype.UUID) error
	DeleteEmailVerificationTokensByUser(ctx context.Context, userID pgtype.UUID) error
	DeleteExpiredEmailVerificationTokens(ctx context.Context) error
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteRefreshToken(ctx context.Context, id pgtype.UUID) error
	DeleteUnverifiedStaleUsers(ctx context.Context) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetAuditLogByComplex(ctx context.Context, arg GetAuditLogByComplexParams) ([]AuditLog, error)
	GetBlockedSlotByID(ctx context.Context, id pgtype.UUID) (BlockedSlot, error)
	GetBlockedSlots(ctx context.Context, arg GetBlockedSlotsParams) ([]BlockedSlot, error)
	// GetBookedSlots returns the hours already taken on the given courts and date.
	//
	// Its status predicate must stay identical to releasedBookingStatuses in
	// internal/data/slotguard and to the WHERE clause on
	// bookings_no_overlapping_span (db/migrations/001_init.sql). Those three are one
	// predicate written three times, because a constraint inside Postgres cannot
	// read a Go constant and a file compiled by sqlc cannot concatenate one.
	// History for why the count matters: this query was named GetAvailableSlots and
	// excluded only 'cancelled' while slotTaken excluded 'cancelled' and 'no_show',
	// so a no_show slot was drawn as taken, passed the overlap check as free, and
	// was refused by the index as a duplicate — three answers to one question.
	//
	// The fourth copy, idx_bookings_no_double, is gone: the exclusion constraint dropped
	// it once the exclusion constraint made it redundant.
	// Two instants, not a date and two times of day. A booking that runs past
	// midnight has no single time of day that says which day its end belongs to,
	// and the caller comparing "23:00" against "01:00" lexicographically is exactly
	// the shape that made a 23:00 booking invisible to the guard meant to see it
	// (the retired CHECK (start_time < end_time)). lower/upper come off the same span the exclusion
	// constraint enforces, so what the storefront greys out and what the write path
	// refuses are read from one value.
	//
	// Matching on `span && local_day(day)` rather than `date = day`: a court
	// occupied until 01:00 is occupied on that morning's grid too. See
	// local_day() in db/migrations/001_init.sql for why "occupies day X" beat "started on day X".
	//
	// payment_expiry_seconds is the configured payment hold (Config.PaymentExpiry,
	// default 15 minutes — see internal/stores), passed as a parameter
	// rather than baked in as INTERVAL '15 minutes' for the same reason slotTaken
	// in internal/data/slotguard takes hold as an argument: this carve-out and
	// the insert-time collision guard have to agree on the same number, or a
	// pending booking between the two configured values shows as free here and
	// taken there (or the reverse). Both now read Config.PaymentExpiry once.
	GetBookedSlots(ctx context.Context, arg GetBookedSlotsParams) ([]GetBookedSlotsRow, error)
	//
	// The tenant predicate is the explicit half of the isolation the row-level
	// security policies enforce (db/migrations/001_init.sql). RLS is the guarantee;
	// this is the statement saying out loud which tenant the row is supposed to
	// belong to, so a lookup by id cannot reach across tenants even if a policy is
	// ever relaxed, dropped, or bypassed for a path that did not need the bypass.
	//
	// It is optional, and the NULL branch is not a loophole: it is exactly the set
	// of callers that legitimately have no tenant on the context — the cron sweeps,
	// the superadmin console, the MercadoPago webhook resolving its payment, the
	// public link resolving its booking. Those run under app.bypass_tenant, so RLS
	// lets them through anyway and a mandatory predicate here would only break
	// them. The store passes data.TenantFromContext's answer; a scoped caller gets
	// the filter, a bypassed one is exactly where it was.
	GetBookingByID(ctx context.Context, arg GetBookingByIDParams) (Booking, error)
	// Locks the booking row for the duration of the enclosing transaction.
	// The refund recorder reads status, notes and deposit_amount back under this
	// lock and writes them straight through, so a concurrent booking update cannot
	// interleave with the money write or erase the deposit. This row lock is the
	// serialization on this table now that the `version` counter is gone: it is
	// held by the database for the whole transaction, which is what the counter
	// only pretended to be.
	//
	// Tenant-scoped like GetBookingByID above, and optional for the same reason.
	GetBookingByIDForUpdate(ctx context.Context, arg GetBookingByIDForUpdateParams) (Booking, error)
	GetBookingsByComplex(ctx context.Context, arg GetBookingsByComplexParams) ([]Booking, error)
	GetBookingsByCourt(ctx context.Context, arg GetBookingsByCourtParams) ([]Booking, error)
	// GetBookingsForReminder2h returns the confirmed bookings whose game starts
	// within the next two hours and that have not been reminded yet.
	//
	// The window is expressed over booking_starts_at (db/migrations/001_init.sql), the one
	// place date and start_time are combined into an instant, and must stay that
	// way: the predicate this replaced compared times of day
	// (`start_time <= (now::time + INTERVAL '2 hours')`), which wraps at 23:00 into
	// `start_time <= 01:00 AND start_time > 23:00` and selects nothing, so no
	// booking in the last two hours of the day was ever reminded. Two timestamptz
	// values have no midnight between them.
	//
	// `now` is a parameter rather than NOW() so the caller owns the clock — the
	// same reason GetForReminder2hEnriched in internal/bookings/store/bookings.go takes one.
	// A window keyed to whenever the test suite happened to run is a window nobody
	// can test at 23:00.
	GetBookingsForReminder2h(ctx context.Context, now pgtype.Timestamptz) ([]Booking, error)
	GetCashMovementByID(ctx context.Context, arg GetCashMovementByIDParams) (CashMovement, error)
	GetCashSessionByID(ctx context.Context, arg GetCashSessionByIDParams) (CashSession, error)
	// Every write against a session (a movement, a void, the close itself) takes
	// this lock first, in the same transaction as the write, so a movement
	// cannot land in a session that is being closed concurrently and a session
	// cannot be closed twice.
	GetCashSessionByIDForUpdate(ctx context.Context, arg GetCashSessionByIDForUpdateParams) (CashSession, error)
	// Tenant-scoped: see the note on GetBookingByID in bookings.sql for why the
	// predicate is optional.
	GetClientByID(ctx context.Context, arg GetClientByIDParams) (GetClientByIDRow, error)
	GetClientByPhone(ctx context.Context, arg GetClientByPhoneParams) (GetClientByPhoneRow, error)
	GetClientsByComplex(ctx context.Context, arg GetClientsByComplexParams) ([]Client, error)
	// Reads active_complexes, not the table: this is the lookup behind the owner
	// guard, the public booking link and the payment paths, and none of them may
	// ever resolve a soft-deleted venue. See the soft-delete cascade in db/migrations/001_init.sql.
	GetComplexByID(ctx context.Context, id pgtype.UUID) (ActiveComplex, error)
	// Reads active_complexes: the slug is the public URL, so this is the storefront.
	// A deleted venue keeps its slug (the name stays reserved) and must answer 404,
	// not serve a page. See the soft-delete cascade in db/migrations/001_init.sql.
	GetComplexBySlug(ctx context.Context, slug string) (ActiveComplex, error)
	//
	// Carries a court count, because a complex with no courts can take no booking
	// at all — it looked identical to a finished one.
	//
	// A COUNT, not a "complete" flag: complete is a policy that moves every time a
	// step is added to onboarding, and a flag would put that policy in the server
	// where the client cannot see it change. The server says how many courts there
	// are; what that means is the caller's business.
	//
	// Soft-deleted courts do not count. Deactivated ones do: a venue that switched
	// a court off still has courts, and that is a different question. Neither do
	// the courts of a soft-deleted venue, but that is now true by construction:
	// active_courts cannot contain one.
	//
	// A scalar subquery rather than a LEFT JOIN and a GROUP BY. Reading from the
	// views means `GROUP BY c.id` no longer covers the other columns: PostgreSQL's
	// functional-dependency shortcut applies to a base table's primary key, and a
	// view has none, so the join form needs all 26 columns spelled into the GROUP
	// BY. The subquery says the same thing in one line and cannot drift from the
	// column list.
	GetComplexesByOwner(ctx context.Context, ownerID pgtype.UUID) ([]GetComplexesByOwnerRow, error)
	// Reads active_courts: a court whose complex was soft-deleted is not a court
	// anyone may book, edit or price, and filtering only on the court's own
	// deleted_at missed exactly that case. See the soft-delete cascade in db/migrations/001_init.sql.
	// Tenant-scoped: see the note on GetBookingByID in bookings.sql for why the
	// predicate is optional.
	GetCourtByID(ctx context.Context, arg GetCourtByIDParams) (ActiveCourt, error)
	GetCourtPrices(ctx context.Context, courtID pgtype.UUID) ([]CourtPrice, error)
	// Ordered naturally rather than lexically: courts are almost always named
	// "Cancha 1", "Cancha 2", ... "Cancha 10", and a plain ORDER BY name sorts
	// "Cancha 10" before "Cancha 2". There is no explicit display-order column,
	// so the numeric part of the name (if any) is extracted and sorted as an
	// integer first, with non-numeric names falling back to plain name order
	// after every numbered court.
	GetCourtsByComplex(ctx context.Context, complexID pgtype.UUID) ([]ActiveCourt, error)
	GetEmailVerificationToken(ctx context.Context, tokenHash []byte) (EmailVerificationToken, error)
	GetLatestEmailVerificationTokenByUser(ctx context.Context, userID pgtype.UUID) (EmailVerificationToken, error)
	// Kept for backwards compatibility with generated code. No longer used by business logic.
	GetNextBookingByClientPhone(ctx context.Context) (Booking, error)
	// The read-only "current session" lookup — GET /current — never locks.
	GetOpenCashSessionByComplex(ctx context.Context, complexID pgtype.UUID) (CashSession, error)
	// Locks the row (if any) so a second open cannot race the check-then-insert:
	// the caller still relies on idx_cash_sessions_one_open for the actual
	// guarantee (this SELECT can only lock a row that already committed), but
	// taking the lock here means a concurrent close sees this transaction's
	// intent before either commits.
	GetOpenCashSessionForUpdate(ctx context.Context, complexID pgtype.UUID) (CashSession, error)
	// A booking can legitimately have more than one payment row (the checkout row plus a
	// cash row inserted by ConfirmPayment), and idx_payments_booking is not unique, so
	// without an explicit order the driver returns an arbitrary row. Prefer the MercadoPago
	// row: it is the one carrying mp_payment_id, which the refund path needs.
	GetPaymentByBookingID(ctx context.Context, bookingID pgtype.UUID) (Payment, error)
	// Tenant-scoped: see the note on GetBookingByID in bookings.sql for why the
	// predicate is optional.
	GetPaymentByIDForUpdate(ctx context.Context, arg GetPaymentByIDForUpdateParams) (Payment, error)
	GetPaymentByMPID(ctx context.Context, mpPaymentID pgtype.Text) (Payment, error)
	GetProductByID(ctx context.Context, arg GetProductByIDParams) (Product, error)
	// Every write against a product (an update, a restock, an adjustment) locks
	// the row first, in the same transaction as the write, so stock_on_hand can
	// never be read-modify-written by two requests at once.
	GetProductByIDForUpdate(ctx context.Context, arg GetProductByIDForUpdateParams) (Product, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash []byte) (RefreshToken, error)
	GetSaleByID(ctx context.Context, arg GetSaleByIDParams) (Sale, error)
	// Void locks the row first, in the same transaction as the write, so two
	// concurrent void attempts on the same sale cannot both read voided_at IS
	// NULL and both proceed — the same reasoning
	// GetCashSessionByIDForUpdate's own comment gives for cash_sessions.
	GetSaleByIDForUpdate(ctx context.Context, arg GetSaleByIDForUpdateParams) (Sale, error)
	GetSchedulesByComplex(ctx context.Context, complexID pgtype.UUID) ([]ComplexSchedule, error)
	// Kept for backwards compatibility with generated code. No longer used by business logic.
	GetUnconfirmedAfterReminder(ctx context.Context) ([]Booking, error)
	GetUsedRefreshTokenByHash(ctx context.Context, tokenHash []byte) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserIdentitiesByUser(ctx context.Context, userID pgtype.UUID) ([]UserIdentity, error)
	GetUserIdentityByProviderSubject(ctx context.Context, arg GetUserIdentityByProviderSubjectParams) (UserIdentity, error)
	IncrementNoShowCount(ctx context.Context, id pgtype.UUID) error
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error)
	InsertBooking(ctx context.Context, arg InsertBookingParams) (Booking, error)
	// Serves both an ordinary movement (voids_movement_id NULL) and a void
	// (voids_movement_id set): cash_movements_check_void (003_cashbox.sql)
	// enforces every void invariant that needs to read the original row, so this
	// query is deliberately the same one call for both.
	InsertCashMovement(ctx context.Context, arg InsertCashMovementParams) (CashMovement, error)
	InsertCashSession(ctx context.Context, arg InsertCashSessionParams) (CashSession, error)
	InsertClient(ctx context.Context, arg InsertClientParams) (Client, error)
	InsertComplex(ctx context.Context, arg InsertComplexParams) (Complex, error)
	InsertCourt(ctx context.Context, arg InsertCourtParams) (Court, error)
	InsertCourtPrice(ctx context.Context, arg InsertCourtPriceParams) (CourtPrice, error)
	InsertEmailVerificationToken(ctx context.Context, arg InsertEmailVerificationTokenParams) (EmailVerificationToken, error)
	InsertPayment(ctx context.Context, arg InsertPaymentParams) (Payment, error)
	InsertProduct(ctx context.Context, arg InsertProductParams) (Product, error)
	InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (RefreshToken, error)
	InsertSale(ctx context.Context, arg InsertSaleParams) (Sale, error)
	InsertSaleItem(ctx context.Context, arg InsertSaleItemParams) (SaleItem, error)
	InsertStockMovement(ctx context.Context, arg InsertStockMovementParams) (StockMovement, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (User, error)
	// Idempotent: a repeated Google sign-in re-links the same (provider,
	// subject) or (user_id, provider) pair and this is a silent no-op — see the
	// unique constraints on user_identities in db/migrations/001_init.sql.
	InsertUserIdentity(ctx context.Context, arg InsertUserIdentityParams) error
	// Atomic: deletes stale tokens (>3 min), inserts new only if none within 3 min.
	InsertVerificationTokenWithCooldown(ctx context.Context, arg InsertVerificationTokenWithCooldownParams) (EmailVerificationToken, error)
	// Oldest first: a session's ledger reads top to bottom like a receipt tape.
	// Not paginated — a shift's movement count is bounded by a business day at
	// the counter, the same reasoning ListBlockedSlots' unpaginated call applies.
	ListCashMovementsBySession(ctx context.Context, arg ListCashMovementsBySessionParams) ([]CashMovement, error)
	// Keyset pagination, same shape as audit_log's listAuditLogsSQL: has_cursor
	// is false on the first page, so the OR's left side short-circuits instead of
	// comparing against a zero-value timestamp.
	ListCashSessionsByComplex(ctx context.Context, arg ListCashSessionsByComplexParams) ([]CashSession, error)
	// Connected complexes whose OAuth token has no known expiry (never recorded
	// one, e.g. rows connected before this column existed) or expires within 30
	// days. cronRefreshMPTokens used to refresh every connected complex on every
	// 12h tick regardless of how recently its token was issued; this narrows
	// that to the complexes that actually need it.
	ListComplexesNeedingMPRefresh(ctx context.Context) ([]ActiveComplex, error)
	// Every payment row of a booking, oldest first (the deposit before the balance),
	// for callers that need the whole ledger rather than one row — the refund path
	// sums money and the booking detail shows each payment; GetPaymentByBookingID's
	// single MercadoPago-preferred row is for callers that need that one row.
	ListPaymentsByBookingID(ctx context.Context, bookingID pgtype.UUID) ([]Payment, error)
	// Not paginated — a shop's catalog is bounded the same way a complex's court
	// list is (internal/courts/store's GetByComplex). has_active_filter is false
	// when the caller asked for every product regardless of active state; the OR's
	// left side short-circuits instead of comparing against a meaningless
	// active_filter value.
	ListProductsByComplex(ctx context.Context, arg ListProductsByComplexParams) ([]Product, error)
	// One sale's own line items, in the order they were inserted — used by Get
	// and by Void (to know which tracked products to restore stock for is a
	// separate query, ListSaleStockMovements, below; this one is for the
	// response shape).
	ListSaleItemsBySale(ctx context.Context, arg ListSaleItemsBySaleParams) ([]SaleItem, error)
	// The batched counterpart to ListSaleItemsBySale, for a page of sales at
	// once (List): one query instead of one per sale on the page.
	ListSaleItemsBySaleIDs(ctx context.Context, arg ListSaleItemsBySaleIDsParams) ([]SaleItem, error)
	// Every stock-tracked line item's original debit for one sale — exactly the
	// set Store.Void must reverse with a 'sale_void' row and a stock_on_hand
	// update. Filtered to kind = 'sale' deliberately: a void's own 'sale_void'
	// rows are inserted, in the same call, against this exact sale_id, and must
	// never be read back by this query as something still needing reversal.
	ListSaleStockMovements(ctx context.Context, arg ListSaleStockMovementsParams) ([]StockMovement, error)
	// Keyset pagination, same shape as cash_sessions' own ListCashSessionsByComplex.
	// has_session_filter is false when the caller asked for every session's
	// sales; the OR's left side short-circuits instead of comparing against a
	// zero-value uuid.
	ListSalesByComplex(ctx context.Context, arg ListSalesByComplexParams) ([]Sale, error)
	// Keyset pagination, same shape as cash_sessions' own ListCashSessionsByComplex.
	ListStockMovementsByProduct(ctx context.Context, arg ListStockMovementsByProductParams) ([]StockMovement, error)
	MarkRefreshTokenUsed(ctx context.Context, tokenHash []byte) error
	MarkReminderSent2h(ctx context.Context, id pgtype.UUID) error
	SetEmailVerified(ctx context.Context, id pgtype.UUID) error
	// :execrows, so the caller can tell "deleted it" from "it was already deleted"
	// without a separate SELECT. complexstore.Store.SoftDeleteCascade is the only caller
	// and runs this inside the transaction that also counts the courts the
	// soft-delete cascade trigger closes.
	SoftDeleteComplex(ctx context.Context, id pgtype.UUID) (int64, error)
	SoftDeleteCourt(ctx context.Context, id pgtype.UUID) error
	// One row per (method, kind, category) combination actually used in the
	// session. The service derives two different things from this same result:
	// the summary's full breakdown (every row, every method), and the cash
	// reconciliation's own income/expense totals (the rows whose method is
	// 'cash' — "Cash reconciliation counts only cash" is a Go-side filter over
	// this query's rows, not a WHERE clause here, because the summary needs the
	// other methods' rows too).
	SumCashMovementsBySession(ctx context.Context, arg SumCashMovementsBySessionParams) ([]SumCashMovementsBySessionRow, error)
	// Unconditional on the row's prior state. What refuses an illegitimate write is
	// the bookings_forbid_status_reversal trigger, which is enforced for every
	// writer rather than for the one query that remembered to check a counter —
	// see the bookings section of db/migrations/001_init.sql for why the counter was removed.
	UpdateBooking(ctx context.Context, arg UpdateBookingParams) (Booking, error)
	// Tenant-scoped: see the note on GetClientByID for why the predicate is optional.
	UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error)
	// H-14: an unconditional UPDATE let two concurrent edits race — each loads the
	// row, applies its own fields, and writes every column back, so whichever
	// request commits second silently overwrites the first's change with a value
	// it read before that first write existed. Both callers got 200 and neither
	// was told.
	//
	// `updated_at = $17` is the optimistic-concurrency precondition: the caller
	// must echo back the `updated_at` it read when it loaded the row. If another
	// write landed in between, that timestamp has already moved and this UPDATE
	// matches zero rows instead of clobbering the other request's change.
	// complexstore.Store.Update turns zero rows into ErrRecordNotFound, which the
	// handler already maps to a 409 edit-conflict response (it previously existed
	// only to cover a row deleted out from under the request) — so a refused
	// update now reaches the caller as a conflict to retry, not as data loss.
	//
	// `expected_version` is the CALLER's precondition, and it is optional (API-08).
	// NULL means "whatever it is now", which is the last-write-wins this endpoint
	// had before versions existed and is what a client that sends no If-Match
	// still gets. A client that does send one and finds the row has moved matches
	// zero rows, the same conflict the timestamp above produces.
	UpdateComplex(ctx context.Context, arg UpdateComplexParams) (Complex, error)
	// expected_version is the caller's optimistic-concurrency precondition and is
	// optional (API-08): NULL is the last-write-wins this endpoint had before
	// versions existed. Zero rows means either the court is gone or somebody else
	// wrote it first; courtstore.Store.Update tells those apart by re-reading.
	UpdateCourt(ctx context.Context, arg UpdateCourtParams) (Court, error)
	UpdateCourtPrice(ctx context.Context, arg UpdateCourtPriceParams) (CourtPrice, error)
	UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (Payment, error)
	// expected_version is the caller's optimistic-concurrency precondition and is
	// optional (API-08): NULL is last-write-wins. Zero rows means either the
	// product is gone or somebody else wrote it first; products/store.Store.Update
	// tells those apart the same way courtstore.Store.Update does (a prior read
	// already proved existence, so a zero-row result here can only be the second
	// case).
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	// Applies a stock movement's signed quantity to the product's own running
	// total, in the same transaction as the movement insert
	// (internal/products/store.Store.Restock / .Adjust), under the FOR UPDATE lock
	// GetProductByIDForUpdate already took. stock_on_hand may go negative — see
	// that column's own comment in db/migrations/004_pos_catalog_stock.sql.
	UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (Product, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpsertSchedule(ctx context.Context, arg UpsertScheduleParams) (ComplexSchedule, error)
	// WHERE voided_at IS NULL is a second, cheap guard against the same race
	// GetSaleByIDForUpdate's lock already closes — see that query's comment and
	// sales_forbid_update_after_void (db/migrations/005_pos_sales.sql) for the
	// third, database-level guard. Zero rows means either the sale is gone (it
	// never is, once inserted) or it was already voided; Store.Void tells those
	// apart the same way cashboxstore.Store.Close does for cash_sessions,
	// because the lock above already proved the row exists moments earlier.
	VoidSale(ctx context.Context, arg VoidSaleParams) (Sale, error)
}

var _ Querier = (*Queries)(nil)
