// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sales.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSaleByID = `-- name: GetSaleByID :one
SELECT id, complex_id, session_id, method, total, cash_movement_id, voided_at, voided_by, void_cash_movement_id, created_at, created_by FROM sales
WHERE id = $1 AND complex_id = $2
`

type GetSaleByIDParams struct {
	ID        pgtype.UUID `json:"id"`
	ComplexID pgtype.UUID `json:"complex_id"`
}

func (q *Queries) GetSaleByID(ctx context.Context, arg GetSaleByIDParams) (Sale, error) {
	row := q.db.QueryRow(ctx, getSaleByID, arg.ID, arg.ComplexID)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.ComplexID,
		&i.SessionID,
		&i.Method,
		&i.Total,
		&i.CashMovementID,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidCashMovementID,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getSaleByIDForUpdate = `-- name: GetSaleByIDForUpdate :one
SELECT id, complex_id, session_id, method, total, cash_movement_id, voided_at, voided_by, void_cash_movement_id, created_at, created_by FROM sales
WHERE id = $1 AND complex_id = $2
FOR UPDATE
`

type GetSaleByIDForUpdateParams struct {
	ID        pgtype.UUID `json:"id"`
	ComplexID pgtype.UUID `json:"complex_id"`
}

// Void locks the row first, in the same transaction as the write, so two
// concurrent void attempts on the same sale cannot both read voided_at IS
// NULL and both proceed — the same reasoning
// GetCashSessionByIDForUpdate's own comment gives for cash_sessions.
func (q *Queries) GetSaleByIDForUpdate(ctx context.Context, arg GetSaleByIDForUpdateParams) (Sale, error) {
	row := q.db.QueryRow(ctx, getSaleByIDForUpdate, arg.ID, arg.ComplexID)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.ComplexID,
		&i.SessionID,
		&i.Method,
		&i.Total,
		&i.CashMovementID,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidCashMovementID,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const insertSale = `-- name: InsertSale :one
INSERT INTO sales (complex_id, session_id, method, total, cash_movement_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, complex_id, session_id, method, total, cash_movement_id, voided_at, voided_by, void_cash_movement_id, created_at, created_by
`

type InsertSaleParams struct {
	ComplexID      pgtype.UUID   `json:"complex_id"`
	SessionID      pgtype.UUID   `json:"session_id"`
	Method         PaymentMethod `json:"method"`
	Total          int32         `json:"total"`
	CashMovementID pgtype.UUID   `json:"cash_movement_id"`
	CreatedBy      pgtype.UUID   `json:"created_by"`
}

func (q *Queries) InsertSale(ctx context.Context, arg InsertSaleParams) (Sale, error) {
	row := q.db.QueryRow(ctx, insertSale,
		arg.ComplexID,
		arg.SessionID,
		arg.Method,
		arg.Total,
		arg.CashMovementID,
		arg.CreatedBy,
	)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.ComplexID,
		&i.SessionID,
		&i.Method,
		&i.Total,
		&i.CashMovementID,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidCashMovementID,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const insertSaleItem = `-- name: InsertSaleItem :one
INSERT INTO sale_items (complex_id, sale_id, product_id, product_name, unit_price, quantity, line_total)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, complex_id, sale_id, product_id, product_name, unit_price, quantity, line_total, created_at
`

type InsertSaleItemParams struct {
	ComplexID   pgtype.UUID `json:"complex_id"`
	SaleID      pgtype.UUID `json:"sale_id"`
	ProductID   pgtype.UUID `json:"product_id"`
	ProductName string      `json:"product_name"`
	UnitPrice   int32       `json:"unit_price"`
	Quantity    int32       `json:"quantity"`
	LineTotal   int32       `json:"line_total"`
}

func (q *Queries) InsertSaleItem(ctx context.Context, arg InsertSaleItemParams) (SaleItem, error) {
	row := q.db.QueryRow(ctx, insertSaleItem,
		arg.ComplexID,
		arg.SaleID,
		arg.ProductID,
		arg.ProductName,
		arg.UnitPrice,
		arg.Quantity,
		arg.LineTotal,
	)
	var i SaleItem
	err := row.Scan(
		&i.ID,
		&i.ComplexID,
		&i.SaleID,
		&i.ProductID,
		&i.ProductName,
		&i.UnitPrice,
		&i.Quantity,
		&i.LineTotal,
		&i.CreatedAt,
	)
	return i, err
}

const listSaleItemsBySale = `-- name: ListSaleItemsBySale :many
SELECT id, complex_id, sale_id, product_id, product_name, unit_price, quantity, line_total, created_at FROM sale_items
WHERE sale_id = $1 AND complex_id = $2
ORDER BY created_at ASC, id ASC
`

type ListSaleItemsBySaleParams struct {
	SaleID    pgtype.UUID `json:"sale_id"`
	ComplexID pgtype.UUID `json:"complex_id"`
}

// One sale's own line items, in the order they were inserted — used by Get
// and by Void (to know which tracked products to restore stock for is a
// separate query, ListSaleStockMovements, below; this one is for the
// response shape).
func (q *Queries) ListSaleItemsBySale(ctx context.Context, arg ListSaleItemsBySaleParams) ([]SaleItem, error) {
	rows, err := q.db.Query(ctx, listSaleItemsBySale, arg.SaleID, arg.ComplexID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SaleItem
	for rows.Next() {
		var i SaleItem
		if err := rows.Scan(
			&i.ID,
			&i.ComplexID,
			&i.SaleID,
			&i.ProductID,
			&i.ProductName,
			&i.UnitPrice,
			&i.Quantity,
			&i.LineTotal,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSaleItemsBySaleIDs = `-- name: ListSaleItemsBySaleIDs :many
SELECT id, complex_id, sale_id, product_id, product_name, unit_price, quantity, line_total, created_at FROM sale_items
WHERE sale_id = ANY($1::uuid[]) AND complex_id = $2::uuid
ORDER BY sale_id, created_at ASC, id ASC
`

type ListSaleItemsBySaleIDsParams struct {
	SaleIds   []pgtype.UUID `json:"sale_ids"`
	ComplexID pgtype.UUID   `json:"complex_id"`
}

// The batched counterpart to ListSaleItemsBySale, for a page of sales at
// once (List): one query instead of one per sale on the page.
func (q *Queries) ListSaleItemsBySaleIDs(ctx context.Context, arg ListSaleItemsBySaleIDsParams) ([]SaleItem, error) {
	rows, err := q.db.Query(ctx, listSaleItemsBySaleIDs, arg.SaleIds, arg.ComplexID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SaleItem
	for rows.Next() {
		var i SaleItem
		if err := rows.Scan(
			&i.ID,
			&i.ComplexID,
			&i.SaleID,
			&i.ProductID,
			&i.ProductName,
			&i.UnitPrice,
			&i.Quantity,
			&i.LineTotal,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSaleStockMovements = `-- name: ListSaleStockMovements :many
SELECT id, complex_id, product_id, kind, quantity, reason, note, cash_movement_id, sale_id, created_at, created_by FROM stock_movements
WHERE sale_id = $1 AND complex_id = $2 AND kind = 'sale'
ORDER BY product_id
`

type ListSaleStockMovementsParams struct {
	SaleID    pgtype.UUID `json:"sale_id"`
	ComplexID pgtype.UUID `json:"complex_id"`
}

// Every stock-tracked line item's original debit for one sale — exactly the
// set Store.Void must reverse with a 'sale_void' row and a stock_on_hand
// update. Filtered to kind = 'sale' deliberately: a void's own 'sale_void'
// rows are inserted, in the same call, against this exact sale_id, and must
// never be read back by this query as something still needing reversal.
func (q *Queries) ListSaleStockMovements(ctx context.Context, arg ListSaleStockMovementsParams) ([]StockMovement, error) {
	rows, err := q.db.Query(ctx, listSaleStockMovements, arg.SaleID, arg.ComplexID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockMovement
	for rows.Next() {
		var i StockMovement
		if err := rows.Scan(
			&i.ID,
			&i.ComplexID,
			&i.ProductID,
			&i.Kind,
			&i.Quantity,
			&i.Reason,
			&i.Note,
			&i.CashMovementID,
			&i.SaleID,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesByComplex = `-- name: ListSalesByComplex :many
SELECT id, complex_id, session_id, method, total, cash_movement_id, voided_at, voided_by, void_cash_movement_id, created_at, created_by FROM sales
WHERE complex_id = $1
  AND (NOT $2::bool OR session_id = $3::uuid)
  AND (NOT $4::bool
       OR (created_at, id) < ($5::timestamptz, $6::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $7::int
`

type ListSalesByComplexParams struct {
	ComplexID        pgtype.UUID        `json:"complex_id"`
	HasSessionFilter bool               `json:"has_session_filter"`
	SessionFilter    pgtype.UUID        `json:"session_filter"`
	HasCursor        bool               `json:"has_cursor"`
	CursorCreatedAt  pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID         pgtype.UUID        `json:"cursor_id"`
	PageLimit        int32              `json:"page_limit"`
}

// Keyset pagination, same shape as cash_sessions' own ListCashSessionsByComplex.
// has_session_filter is false when the caller asked for every session's
// sales; the OR's left side short-circuits instead of comparing against a
// zero-value uuid.
func (q *Queries) ListSalesByComplex(ctx context.Context, arg ListSalesByComplexParams) ([]Sale, error) {
	rows, err := q.db.Query(ctx, listSalesByComplex,
		arg.ComplexID,
		arg.HasSessionFilter,
		arg.SessionFilter,
		arg.HasCursor,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sale
	for rows.Next() {
		var i Sale
		if err := rows.Scan(
			&i.ID,
			&i.ComplexID,
			&i.SessionID,
			&i.Method,
			&i.Total,
			&i.CashMovementID,
			&i.VoidedAt,
			&i.VoidedBy,
			&i.VoidCashMovementID,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const voidSale = `-- name: VoidSale :one
UPDATE sales
SET voided_at = $1, voided_by = $2, void_cash_movement_id = $3
WHERE id = $4 AND complex_id = $5 AND voided_at IS NULL
RETURNING id, complex_id, session_id, method, total, cash_movement_id, voided_at, voided_by, void_cash_movement_id, created_at, created_by
`

type VoidSaleParams struct {
	VoidedAt           pgtype.Timestamptz `json:"voided_at"`
	VoidedBy           pgtype.UUID        `json:"voided_by"`
	VoidCashMovementID pgtype.UUID        `json:"void_cash_movement_id"`
	ID                 pgtype.UUID        `json:"id"`
	ComplexID          pgtype.UUID        `json:"complex_id"`
}

// WHERE voided_at IS NULL is a second, cheap guard against the same race
// GetSaleByIDForUpdate's lock already closes — see that query's comment and
// sales_forbid_update_after_void (db/migrations/005_pos_sales.sql) for the
// third, database-level guard. Zero rows means either the sale is gone (it
// never is, once inserted) or it was already voided; Store.Void tells those
// apart the same way cashboxstore.Store.Close does for cash_sessions,
// because the lock above already proved the row exists moments earlier.
func (q *Queries) VoidSale(ctx context.Context, arg VoidSaleParams) (Sale, error) {
	row := q.db.QueryRow(ctx, voidSale,
		arg.VoidedAt,
		arg.VoidedBy,
		arg.VoidCashMovementID,
		arg.ID,
		arg.ComplexID,
	)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.ComplexID,
		&i.SessionID,
		&i.Method,
		&i.Total,
		&i.CashMovementID,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidCashMovementID,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}
