// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_identities.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserIdentitiesByUser = `-- name: GetUserIdentitiesByUser :many
SELECT id, user_id, provider, subject, email, created_at FROM user_identities
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) GetUserIdentitiesByUser(ctx context.Context, userID pgtype.UUID) ([]UserIdentity, error) {
	rows, err := q.db.Query(ctx, getUserIdentitiesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserIdentity
	for rows.Next() {
		var i UserIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.Subject,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserIdentityByProviderSubject = `-- name: GetUserIdentityByProviderSubject :one
SELECT id, user_id, provider, subject, email, created_at FROM user_identities
WHERE provider = $1 AND subject = $2
`

type GetUserIdentityByProviderSubjectParams struct {
	Provider string `json:"provider"`
	Subject  string `json:"subject"`
}

func (q *Queries) GetUserIdentityByProviderSubject(ctx context.Context, arg GetUserIdentityByProviderSubjectParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, getUserIdentityByProviderSubject, arg.Provider, arg.Subject)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Subject,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const insertUserIdentity = `-- name: InsertUserIdentity :exec
INSERT INTO user_identities (user_id, provider, subject, email)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type InsertUserIdentityParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Provider string      `json:"provider"`
	Subject  string      `json:"subject"`
	Email    pgtype.Text `json:"email"`
}

// Idempotent: a repeated Google sign-in re-links the same (provider,
// subject) or (user_id, provider) pair and this is a silent no-op — see the
// unique constraints in db/migrations/002_user_identities.sql.
func (q *Queries) InsertUserIdentity(ctx context.Context, arg InsertUserIdentityParams) error {
	_, err := q.db.Exec(ctx, insertUserIdentity,
		arg.UserID,
		arg.Provider,
		arg.Subject,
		arg.Email,
	)
	return err
}
